-- Autogenerated sql created by jasonbrown on: 02/15/2016
insert into esl_comp_map (class_id, description)
values ('cesl_16-10001','Locate specific information in words and phrases that are strongly supported by visual context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10002','Locate specific information in a list or sentences in directions, labels, signs, dialogs, or forms.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10003','Locate specific information or definitions, in a short, multi-sentence paragraph, dialog, or form.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10004','Locate specific information or definitions in a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10005','Locate specific information or definitions in a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10006','Locate specific information, definitions, or restatements of concepts in a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10007','Locate specific information, definitions, or restatements of concepts in sections of a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10008','Locate specific information, definitions, or restatements of concepts in a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10009','Recognize essential idioms and idiomatic language in signs.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10010','Recognize essential idioms and idiomatic language in warnings or advisories.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10011','Recognize common idioms and idiomatic language in context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10012','Understand basic common idiomatic language, such as idiomatic expressions, phrasal verbs, semantic clusters, and other collocations supported by contextual clues in a multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10013','Understand common intermediate idiomatic language, such as idiomatic expressions, phrasal verbs, semantic clusters, and other collocations supported by contextual clues in a multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10014','Understand intermediate common idiomatic language, such as idiomatic expressions, phrasal verbs, semantic clusters, and other collocations supported by contextual clues in a two- page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10015','Understand advanced common idiomatic language, such as idiomatic expressions, phrasal verbs, semantic clusters, and other collocations supported by contextual clues in a section of a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10016','Understand advanced idiomatic language, such as idiomatic expressions, phrasal verbs, semantic clusters, and other collocations supported by contextual clues in a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10017','Find a word within a category using images in a picture dictionary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10018','Find related words within a category using images in a picture dictionary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10019','Define unfamiliar words that relate to a category by using a picture dictionary or English learners’ dictionary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10020','Define common, unfamiliar words by using an English learners’ dictionary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10021','Choose the appropriate definition among multiple definitions in an English learners’ dictionary of common words with clear differences between meanings.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10022','Choose the appropriate definition among multiple definitions in an English learners’ dictionary of words with clear differences between meanings.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10023','Choose the appropriate definition among multiple definitions in an English dictionary of words with nuanced differences in meaning.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10024','Choose the appropriate definition among multiple definitions in an English dictionary of academic words with nuanced differences in meaning.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10025','Use visual context to infer the meaning of high frequency sight words or phrases.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10026','Use context to infer the meaning of high frequency sight words or phrases within and across sentences, labels, lists, signs, or forms strongly supported by visual clues, for example by examining the overall meaning of a sentence; a word’s position or function in a sentence; synonyms, antonyms; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10027','Use context to infer the meaning of high frequency sight words or phrases within short, multi-sentence paragraphs supported by visual clues, for example by examining the overall meaning of a sentence; a word’s position or function in a sentence; synonyms, antonyms; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10028','Use context to infer the meaning of a word or phrase within and across a one page authentic or adapted text, for example by examining the overall meaning of a sentence, paragraph, or text; a word’s position or function in a sentence; synonyms, antonyms; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10029','Use context to infer the meaning of a word or phrase within and across a one page multi-paragraph authentic or adapted text, for example by examining the overall meaning of a sentence, paragraph, or text; a word’s position or function in a sentence; synonyms, antonyms; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10030','Use context to infer the meaning of a word or phrase within and across a two-page authentic text, for example by examining the overall meaning of a sentence, paragraph, or text; a word’s position or function in a sentence; synonyms, antonyms, appositives; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10031','Use context to infer the meaning of a word or phrase within and across a section of a multi-page academic fiction or nonfiction chapter, for example by examining the overall meaning of a sentence, paragraph, or text; a word’s position or function in a sentence; synonyms, antonyms, appositives; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10032','Use context to infer the meaning of a word or phrase within and across a multi-page academic fiction or nonfiction chapter, for example by examining the overall meaning of a sentence, paragraph, or text; a word’s position or function in a sentence; synonyms, antonyms, appositives; topic-related vocabulary; causative and other logical relationships.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10033','Use word structures (high frequency prefixes) to infer the meaning of a word or phrase in labels, lists, signs, or forms strongly supported by visual clues.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10034','Use word structures (high frequency prefixes and suffixes) to infer the meaning of a word or phrase within and across sentences, labels, lists, signs, or forms strongly supported by visual clues.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10035','Use word structures (affixes and roots) to infer the meaning of a word or phrase within short, multi-sentence paragraphs supported by visual clues.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10036','Use word structures (affixes and roots) to infer the meaning of a word or phrase within and across a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10037','Use word structures (affixes and roots) to infer the meaning of a word or phrase within and across a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10038','Use word structures (affixes and roots) to infer the meaning of a word or phrase within and across a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10039','Use word structures (affixes and roots) to infer the meaning of a word or phrase within and across a section of a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10040','Use word structures (affixes and roots) to infer the meaning of a word or phrase within and across a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10041','Apply knowledge of basic pronouns to interpret the meaning of phrases and simple sentences.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10042','Apply knowledge of basic conjunctions to interpret the meaning of sentences.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10043','Apply knowledge of demonstratives and possessives to interpret the meaning of short, multi-sentence paragraphs.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10044','Apply knowledge of cohesive devices such as pronoun references, adverbs of time, and conjunctions to interpret the meaning of a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10045','Apply knowledge of basic cohesive devices to interpret the meaning and structure of a one-page, multi-paragraph authentic or adapted text, including conjunctions and conjunctive adverbs in complex sentences and across paragraphs, pronoun reference, relationships of time and agency, passive voice, articles, and use of verb tenses, adverbs, adverbials to establish time of occurrence or sequence.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10046','Apply knowledge of level-appropriate cohesive devices to interpret the meaning and structure of a two-page authentic text, including conjunctions and conjunctive adverbs in complex sentences and across paragraphs, pronoun reference, relationships of time and agency, passive voice, articles, and use of verb tenses, conditionals, adverbs, adverbials to establish time of occurrence or sequence.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10047','Apply knowledge of a range of level-appropriate cohesive devices to interpret the meaning and structure of a section of a multi-page academic fiction or nonfiction chapter, including conjunctions and conjunctive adverbs in complex sentences and across paragraphs, pronoun reference, relationships of time and agency, passive voice, determiners, and use of verb tenses, conditionals, adverbs, adverbials to establish time of occurrence or sequence.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10048','Apply knowledge of a variety of level-appropriate cohesive devices and strategies to evaluate the meaning and structure of a multi-page academic fiction or nonfiction chapter, including conjunctions and conjunctive adverbs in complex sentences and across paragraphs, pronoun reference, relationships of time and agency, passive voice, determiners, and use of verb tenses, conditionals, adverbs, adverbials to establish time of occurrence or sequence.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10049','Identify the purpose of a document, such as a bill, by interpreting words supported by visual cues.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10050','Identify the purpose of a statement, such as a question, traffic ticket, or an advertisement. Respond appropriately to one- to two-step written directions.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10051','Identify the purpose and audience of a short, multi-sentence paragraph, such as permission slips, news reports, narratives, and emails. Respond appropriately to two- to four-step written directions.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10052','Identify the purpose and audience of a one-page authentic or adapted text, such as letters from school, articles, narratives, and brochures.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10053','Identify an author’s point of view, audience, and purpose in a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10054','Identify an author’s point of view, audience, and purpose in a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10055','Evaluate an author’s point of view, audience, and purpose in a section of a multi-page academic fiction or nonfiction chapter and analyze the use of rhetoric and word choice to advance that point of view or purpose.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10056','Evaluate an author’s point of view, audience, and purpose in a multi-page academic fiction or nonfiction chapter and analyze the use of rhetoric, tone, and word choice to advance that point of view or purpose.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10057','Compare items using information supported by visual and contextual clues, such as prices.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10058','Compare items using information supported by visual and contextual clues, such as product or services details.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10059','Compare items using information such as product or services details.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10060','Compare and evaluate quality of information using informational sources such as price lists, bar graphs, and pie charts.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10061','Identify and evaluate statements of fact and opinion, using simple discourse markers of opinion.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10062','Differentiate fact from opinion and evaluate statements of fact and opinion in written materials; recognize discourse markers of opinion and hypothetical constructions.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10063','Delineate and evaluate clear arguments and specific claims in a text, following the line of reasoning to its conclusion; recognize when irrelevant evidence is introduced.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10064','Delineate and evaluate the argument and specific claims in a text, assessing whether the reasoning is sound and the evidence is relevant and sufficient; recognize when irrelevant evidence or bias is introduced.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10065','Identify the general topic, sequence of events, characters, or setting in words and phrases supported by visual context on a familiar topic.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10066','Identify the general topic, sequence of events, characters, or setting in sentences and dialogs supported by images in a familiar context, answering who, what, where, when, and why.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10067','Identify the general topic, sequence of events, characters, or setting in short, multi-sentence paragraphs and dialogs supported by images in a familiar context, answering who, what, where, when, and why.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10068','Identify main and supporting ideas in a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10069','Identify main ideas and supporting details or examples in a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10070','Distinguish main ideas from supporting ideas, within a single document, in a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10071','Distinguish stated or implied main ideas from supporting ideas, within a single document, in a variety of sections of multi-page academic fiction or nonfiction chapters.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10072','Determine a stated or implied main idea, within a single document, in a variety of multi-page academic chapters from different disciplines; identify supporting information and details.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10073','Identify basic features of text including titles, sentences, simple charts, and images in simplified materials such as forms, signs, and calendars strongly supported by visual context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10074','Identify features of text including titles, sentences, simple charts, and images in simplified materials with minimal written text such as schedules, forms, labels, and calendars supported by visual context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10075','Identify features of text including titles, number of paragraphs, simple charts, and graphics in a short, multi-sentence materials such as brochures and simple academic materials.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10076','Identify text type and purpose by reading titles, subtitles, simple charts, and graphics in a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10077','Identify text type, audience, and purpose by reading titles, subtitles, introductions, simple charts, and graphics in a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10078','Identify text type, audience, and purpose by reading titles, subtitles, introductions, charts, and graphics in a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10079','Identify text type, audience, and purpose by reading titles, subtitles, introductions, charts, and graphics in a section of a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10080','Identify text type, audience, and purpose by reading titles, subtitles, introductions, charts, and graphics in a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10081','Identify details and examples in simplified materials such as forms, signs, and calendars strongly supported by visual context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10082','Identify details and examples in simplified materials with minimal written text such as schedules, forms, labels, and calendars supported by visual context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10083','Identify details and examples in short, multi-sentence paragraphs supported by visual clues.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10084','Identify details and examples in a one-page authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10085','Refer to details and examples in a text to explain explicit and implied meaning in a one-page, multi-paragraph authentic or adapted text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10086','Cite textual evidence to support analysis of explicit and implied meaning in a two-page authentic text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10087','Cite several pieces of textual evidence to support analysis of explicit and implied meaning in a section of a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-10088','Cite strong and thorough textual evidence to support analysis of explicit and implied meaning in a multi-page academic fiction or nonfiction chapter.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20001','Print numerals and upper and lowercase letters of the alphabet.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20002','Write words and combine them into phrases and simple sentences based on visual prompts.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20003','Write a series of simple related sentences in stories or dialogs.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20004','Compose simple sentences about daily activities.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20005','Construct simple, compound, and complex sentences using adverbial clauses.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20006','Vary sentence patterns, including simple, compound, and complex sentences, including adverbial and adjectival clauses, with general control over sentence boundaries.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20007','Expand and combine simple sentences by adding modifying words and phrases, as well as adverbial, adjectival, and noun clauses.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20008','Use appropriate and varied sentence patterns with transitions, coordination, and subordination, including reduced clauses to create cohesion and clarify the relationships among ideas and concepts.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20009','Group words together into a list or category.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20010','Write simple sentences on one topic based on previously learned vocabulary and structures.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20011','Write a series of simple sentences on one topic based on previously learned vocabulary and structures; use affirmative, negative, and question forms appropriately.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20012','Write a loosely organized paragraph or dialog based on personal experiences or familiar material, based on a visual or written prompt.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20013','Write a well-developed paragraph that includes a topic sentence, supporting detail, and a conclusion.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20014','Write expository essays with multiple paragraphs, with a thesis, supporting details, and a conclusion, referring to the ideas of others.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20015','Write expository essays with a clear introduction, supporting details, and conclusion, using a variety of rhetorical techniques and coherent organization. Integrate the ideas of others using in-text citations to support the writer’s thesis.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20016','Write expository essays and papers with depth, complexity, and logical reasoning that include facts, examples, supporting details, and references to outside sources. Integrate the ideas of others through paraphrase, summary, quotation, and a works cited or references page, including multiple sources, to support the writer’s thesis.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20017','Use common words related to life, work, and classroom vocabulary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20018','Use common phrases related to life, work, and classroom vocabulary.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20019','Use a range of words and phrases related to academic and career topics adequately.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20020','Use a range of words and phrases related to academic and career topics appropriately.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20021','Use a range of words and phrases related to academic and career topics effectively.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20022','Use a range of college-level academic words and phrases adequately.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20023','Use a range of college-level academic words and phrases appropriately.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20024','Use a wide range of college-level academic words and phrases effectively.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20025','Check copied work for accuracy.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20026','Edit writing for spelling and basic grammatical form.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20027','Edit writing for basic capitalization, end punctuation, basic grammatical form, and spelling.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20028','Edit writing for capitalization, sentence punctuation, basic grammatical form, and spelling.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20029','Edit writing for capitalization, sentence punctuation, sentence boundaries, grammatical form, and spelling.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20030','Edit writing for content, capitalization, punctuation of varied sentence types, grammatical form, and spelling.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20031','Edit writing for content, word choice, mechanics, capitalization, punctuation of varied sentence types, grammatical form, and spelling.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-20032','Edit writing for content, sentence variety, organization, word choice, mechanics, capitalization, punctuation of varied sentence types, grammatical form, and spelling. Choose the correct synonym in a thesaurus to replace overused words in a text.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30001','Uses subjects and verbs in all clauses; Uses stative verbs and expletive there + be, expletive it +be when needed; Uses noun phrase subject without pronoun repetition; Uses standard SV(O) word order');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30002','Uses subjects and verbs in all clauses; Uses stative verbs and expletive there + be, expletive it +be as appropriate; Uses noun phrase subject without pronoun repetition');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30003','Uses inverted word order appropriately after nor, only, never, and not; Uses inverted word order appropriately with prepositional phrases of location or other adverb phrases; Uses complex noun phrase subject without pronoun repetition');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30004','Creates yes/no questions with appropriate word order; Creates yes/no questions with auxiliary verbs; Creates wh- questions with appropriate word order; Creates wh- questions with verbs/auxiliary verbs; Uses auxiliaries correctly in short answers');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30005','Creates wh- questions with appropriate word order; Creates wh- questions with verbs/auxiliary verbs; Understands, uses, and answers tag questions; Uses auxiliaries correctly in short answers');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30006','Creates embedded yes/no or wh- questions using appropriate word order; Uses auxiliaries correctly in short answers');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30007','Creates negative statements');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30008','Creates negative statements with negative polarity (avoiding “double negatives”); Creates negative questions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30009','Creates negative statements with negative polarity with adverbials such as hardly and rarely; Creates negative questions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30010','Creates negative imperatives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30011','Creates imperatives with separable transitive verbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30012','Creates embedded imperatives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30013','Uses direct and indirect objects');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30014','Uses pronoun/noun phrase order with prepositions in direct and indirect object');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30015','Uses correct word order of direct and indirect objects');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30016','Uses common adjectives before nouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30017','Uses adjectives of frequency before nouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30018','Uses the appropriate order of multiple adjectives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30019','Uses common adverbs in the correct order');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30020','Uses adverbs of frequency in the correct position');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30021','Uses the correct placement of adverb phrases');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30022','Forms and uses basic verb tenses in familiar contexts: Simple present, Present progressive, Simple past, Future with going to, Future with will; Uses present vs. present progressive in appropriate contexts; Uses present vs. past in appropriate contexts; Uses present vs. future in appropriate contexts; Forms and uses basic irregular verbs correctly; Uses stative verb when required');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30023','Forms and uses verb tenses appropriately, including in contexts requiring: Simple present and present progressive, Simple past and past progressive, Present perfect and present perfect progressive, Past perfect and past perfect progressive, Simple future with will and going to, Future progressive, Habitual past with used to; Uses present vs. present progressive appropriately in contrast; Uses past vs. present perfect appropriately; Uses past vs. past progressive appropriately; Uses past vs. past perfect appropriately; Uses appropriate sequence of tenses in sentences and in short multi-sentence texts; Forms and uses common irregular verbs correctly; Uses simple tenses appropriately with stative verbs; Differentiates between action vs. stative quality of the same verb and uses simple vs. progressive appropriately');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30024','Forms and uses a variety of verb tenses appropriately, including in contexts requiring: Simple present and present progressive, Simple past and past progressive, Present perfect and present perfect progressive, Past perfect and past perfect progressive, Variety of verb tenses to express future (present, present progressive, and the use of be going to, will), Future progressive, Habitual past with would; Distinguishes between and uses appropriately simple vs. progressive; Distinguishes between and uses appropriately simple vs. perfect tenses; Uses tenses consistently and sequences tense appropriately in reported speech and in multi-sentence texts; Differentiates between action vs. stative quality of the same verb and uses simple vs. progressive appropriately');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30025','Uses basic modals in present affirmative and negative forms with simple form of verb');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30026','Uses a range of present modals; Uses modals to express the past');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30027','Uses a range of present and past modals; Uses modals to express appropriate register');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30028','Applies subject-verb agreement when verb directly follows subject; Applies subject-verb agreement with quantifier + noun subjects; Applies subject-verb agreement with compound subjects with and');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30029','Applies subject-verb agreement when verb closely follows subject; Applies subject-verb agreement when verb is separated from subject by a clause or phrase, or in correlatives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30030','Applies subject-verb agreement with a variety of subjects, including multiple subjects, gerunds and infinitives, quantifier + noun, relative pronoun when subject is separated by clause/phrase; Applies subject-verb agreement inside relative clauses');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30031','Forms and uses basic passive constructions in familiar contexts');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30032','Forms and uses passive constructions with correct auxiliary verb and past participle form: Determine whether agency requires active or passive construction, Use passive voice when appropriate; Forms and uses only transitive verbs in the passive voice');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30033','Forms and uses passive constructions appropriately in a variety of contexts: Determine whether agency requires active or passive construction, Use passive/active voice when appropriate; Forms and uses passive causative structures appropriately');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30034','DELETED');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30035','Uses common causative constructions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30036','Uses a range of causative constructions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30037','Uses common phrasal verbs; Uses basic phrasal verbs with object pronouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30038','Uses phrasal verbs with the correct particle; Uses separable and inseparable phrasal verbs with object pronouns; Uses correct spelling and form of irregular verbs; Uses correct form of intransitive verbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30039','Uses phrasal verbs with the correct particle; Uses a variety of verb-complement patterns; Uses subjunctive where appropriate; Uses transitive and intransitive verbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30040','Uses common gerunds and infinitives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30041','Uses gerunds and infinitives as subjects and objects; Use gerunds and infinitives with appropriate verbs; Uses infinitives with too and enough');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30042','Uses gerunds and infinitives, including perfect infinitives, in a range of contexts (e.g., as subjects, objects of prepositions, and verb complements).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30043','Uses appropriate singular or plural forms; Uses the appropriate quantifiers and comparatives for common count vs. noncount nouns; Uses the appropriate partitives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30044','Distinguishes between count and non-count nouns (as evidenced by appropriate subject-verb agreement and pronoun reference); Uses appropriate singular or plural forms; Uses the appropriate quantifiers and comparatives for count vs. noncount nouns; Uses the appropriate partitives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30045','Uses appropriate singular or plural forms; Uses the appropriate quantifiers and comparatives for abstract and concrete count vs. noncount nouns; Uses the appropriate partitives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30046','Uses personal subject/object pronouns; Uses reflexive pronouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30047','Uses reflexive pronouns; Uses indefinite pronouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30048','Uses unambiguous pronoun reference with multiple possible antecedents; Uses correct pronoun antecedent agreement with singular words that end in –s; Uses correct pronoun reference with noun separated from the pronoun by a prepositional phrase or relative clause');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30049','Uses possessive adjectives with nouns; Distinguishes possessive adjectives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30050','Uses apostrophe with nouns to indicate possession; Distinguishes he’s from his and it’s from its');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30051','Uses a range of possessive nouns and adjectives correctly');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30052','Uses appropriate form of common single-word adjectives');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30053','Understands appropriate form of a range of adjectives; Distinguishes intermediate-level present vs. past participles as adjectives; Distinguishes between almost and most');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30054','Uses appropriate form of a range of adjectives; Distinguishes advanced-level present vs. past participles as adjectives; Uses appropriate form and placement of a range of present and past participial phrases.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30055','Uses definite and indefinite articles with count nouns; Uses demonstrative determiners; Uses common quantifiers; Uses null article appropriately for cities');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30056','Uses definite and indefinite articles with count nouns; Uses demonstrative determiners; Uses quantifiers indicating amount appropriately with count and noncount nouns; Uses a and the for first and second mentions; Uses articles appropriately for countries');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30057','Uses definite and indefinite articles appropriately in a range of contexts, including abstract nouns and generic vs. specific nouns; Uses the definite article appropriately for places');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30058','Uses capitalization for proper nouns and titles');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30059','Uses appropriate capitalization');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30060','Uses appropriate capitalization');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30061','Uses common prepositions of time and location + noun/noun phrase');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30062','Uses prepositions of time and location + noun/noun phrase');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30063','Uses a variety of prepositional phrases in a range of constructions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30064','Creates basic compound sentences using coordinating conjunctions; Creates simple and basic compound sentences using coordinating conjunctions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30065','Uses conjunctions to make compound sentences with parallel structures; Creates complex sentences using a range of subordinating conjunctions; Creates sentences using correlative conjunctions; Uses conjunctive adverbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30066','Creates simple, compound, complex, and compound-complex sentences with correct word order and parallel structures; Uses conjunctive adverbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30067','Creates time phrases using common subordinating conjunctions of time, and reason');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30068','Creates sentences with adverbial clauses of time and reason; Creates  simple adjective clauses; Creates noun clauses; Creates conditionals, including: Present real, Future real, Wish/hope');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30069','Creates sentences with a range of adjective, adverb, and noun clauses as well as embedded questions correctly; Creates reduced adjective clauses; Creates reduced adverbial clauses; Creates a variety of types of conditional sentences appropriately; Creates conditionals, including: Present unreal, Past unreal');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30070','Creates simple comparative sentences and intensifiers');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30071','Creates comparative sentences, including use of superlatives, intensifiers, and as … as constructions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-30072','Creates a variety of comparative sentences appropriately');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40001','Identify high-frequency spoken words by selecting a related image');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40002','Use context to determine the meaning of words or phrases in a listening passage appropriate for this level');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40003','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40004','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level. Structures: Negatives, Common connectors, Pronouns');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40005','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level. Structures: Definitions, Negatives, Connectors, Expressions of time, Present and future real conditions, Adjective clauses, Synonyms');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40006','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level. Structures: Appositives/Definitions/Adjective clauses, Negatives, Connectors, Synonyms/antonyms');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40007','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level. Structures: Negatives, Conjunctive adverbs');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40008','Use context to infer the meaning of words or phrases in a listening passage appropriate for this level. Structures: Past unreal conditional');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40009','Determine meaning of basic phrasal verbs describing physical actions in context');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40010','Determine meaning of frequently used classroom idioms and phrasal verbs in context');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40011','Determine meaning of frequently used idioms and phrasal verbs in context');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40012','Determine meaning of frequently used idioms and phrasal verbs in clear contexts');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40013','Determine meaning of frequently used idioms and phrasal verbs in context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40014','Determine meaning of idioms and figurative language in clear contexts.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40015','Determine meaning of less frequent idioms and figurative language in context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40016','Determine meaning of complex, low-frequency idioms and figurative language in context.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40017','Identify the general topic or setting in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40018','Identify the general topic, sequence of events, characters, or setting in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40019','Identify the general topic, sequence of events, characters, or setting in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40020','Identify the main idea and supporting details in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40021','Identify stated or implied main ideas and supporting details in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40022','Identify ideas and supporting details in a listening passage appropriate for this level.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40023','Distinguish stated or implied main ideas from supporting details in a listening passage appropriate for this level');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40024','Distinguish stated or implied main ideas from supporting details in a listening passage appropriate for this level');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40025','Recognize that a response is expected when asked a question');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40026','Distinguish between a question or statement of fact in a sentence fragment, based on tone or mood');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40027','Distinguish between a question and a statement in a simple sentence, based on tone or mood regardless or word order');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40028','Distinguish between a yes/no question and a question for information, based on a variation in tone or mood');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40029','Distinguish meaning and intent based on variation in tone or mood');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40030','Distinguish meaning and points of emphasis in questions or statements, based on stress, tone, or mood regardless of word order');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40031','Distinguish between a question and a statement regardless of word order and identify points of emphasis, tone, or mood based on intonation');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40032','Identify points of emphasis, tone, or mood based on stress and intonation');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40033','Respond appropriately to single word commands');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40034','Respond appropriately to high frequency, multi-word commands and social expressions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40035','Respond appropriately to multi-word commands and social expressions');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40036','Respond appropriately to short instructions.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40037','Respond appropriately to instructions and simple rules or options presented orally, such as a telephone audio directory.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40038','Respond appropriately to oral announcements and instructions that include multiple details.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40039','Respond appropriately to detailed specific spoken instructions on an academic topic.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40040','Respond appropriately to detailed specific spoken instructions on academic and technical topics.');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40041','Identify a speaker’s purpose in a listening passage appropriate for this level (e.g., simple conversation with visual cues)');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40042','Identify a speaker’s purpose in a listening passage appropriate for this level (e.g., simple conversation, no visual cues).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40043','Identify a speaker’s purpose in a listening passage appropriate for this level (e.g., simple phone conversation)');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40044','Identify a speaker’s purpose in a listening passage appropriate for this level (e.g., conversation with visual cues).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40045','Identify a speaker’s purpose or points of emphasis in a listening passage appropriate for this level (e.g., a recorded message).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40046','Identify a speaker’s purpose, point of view, or points of emphasis in a listening passage appropriate for this level (e.g., a contextualized conversation).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40047','Identify a speaker’s purpose, point of view, use of evidence, or points of emphasis in a listening passage appropriate for this level (e.g., a college lecture, a complex conversation).');

insert into esl_comp_map (class_id, description)
values ('cesl_16-40048','Identify a speaker’s purpose, point of view, use of evidence, points of emphasis, or tone in a listening passage appropriate for this level (e.g., a political speech).');

