-- Autogenerated sql created by jasonbrown on: 02/15/2016

insert into math_comp_map (class_id, description)
values ('cmath16-10001','Write, read, and evaluate expressions in which letters stand for numbers.');

insert into math_comp_map (class_id, description)
values ('cmath16-10002','Use variables to represent numbers and write expressions when solving a non-contextual or contextual problem; understand that a variable can represent an unknown number, or, depending on the purpose at hand, any number in a specified set.');

insert into math_comp_map (class_id, description)
values ('cmath16-10003','Identify expressions that represent a quantity in terms of its mathematical context.');

insert into math_comp_map (class_id, description)
values ('cmath16-10004','Identify parts of an expression, such as terms, factors, coefficients, exponents, and base.');

insert into math_comp_map (class_id, description)
values ('cmath16-10005','Determine the equation of a line given information such as two points on the line, a point on the line and the slope, or a table of values, without context.');

insert into math_comp_map (class_id, description)
values ('cmath16-10006','Determine the rate of change and initial value of the equation from a description of a relationship or from two (x, y) values, including reading these from a table or from a graph. Interpret the rate of change and initial value of a linear equation in terms of the situation it models, and in terms of its graph or a table of values.');

insert into math_comp_map (class_id, description)
values ('cmath16-10007','Construct a linear equation in one variable to model a verbal description of a contextual situation.');

insert into math_comp_map (class_id, description)
values ('cmath16-10008','Use variables to represent two quantities in a contextual problem that change in relationship to one another; write an equation to express one quantity, thought of as the dependent variable, in terms of the other quantity, thought of as the independent variable. Analyze the relationship between the dependent and independent variables using graphs and tables, and relate these to the equation.');

insert into math_comp_map (class_id, description)
values ('cmath16-10009','Construct simple linear inequalities of the form px + q > r  or px + q < r, where p, q, and r are specific rational numbers.');

insert into math_comp_map (class_id, description)
values ('cmath16-10010','Identify expressions that represent a quantity in terms of its mathematical context.');

insert into math_comp_map (class_id, description)
values ('cmath16-10011','Identify parts of an expression, such as degree, index, complex numbers, imaginary part, real part, and log.');

insert into math_comp_map (class_id, description)
values ('cmath16-10012','Write a function, using function notation, that describes a relationship between two quantities.');

insert into math_comp_map (class_id, description)
values ('cmath16-10013','Convert between multiple representations of linear models in authentic contextual situations, using tables of ordered pairs, graphs, equations, and verbal descriptions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10014','Given the equation of a linear function, write the inverse of the function.');

insert into math_comp_map (class_id, description)
values ('cmath16-10015','Represent constraints by equations or inequalities, and by systems of equations and/or inequalities.');

insert into math_comp_map (class_id, description)
values ('cmath16-10016','Construct a function to model a relationship between two quantities that is quadratic, square root, exponential, logarithmic, or periodic.');

insert into math_comp_map (class_id, description)
values ('cmath16-10017','Compose functions. Describe the domain of the composed function with respect to the domains of original functions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10018','Convert between multiple representations of a piecewise-defined relationship using graphs, equations, and verbal descriptions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10019','Simplify/evaluate numerical expressions using order of operations.');

insert into math_comp_map (class_id, description)
values ('cmath16-10020','Understand that expressions that simplify to zero in the denominator are undefined.');

insert into math_comp_map (class_id, description)
values ('cmath16-10021','Understand that expressions that simplify to zero in the numerator with a non-zero denominator have a value of zero.');

insert into math_comp_map (class_id, description)
values ('cmath16-10022','Simplify/evaluate algebraic expressions using basic operations and order of operations.');

insert into math_comp_map (class_id, description)
values ('cmath16-10023','Apply properties of operations as strategies to add, subtract, factor, and expand linear and polynomial expressions with rational coefficients, including simplifying the result.');

insert into math_comp_map (class_id, description)
values ('cmath16-10024','Choose and produce an equivalent form of an expression or equation to reveal and explain properties of the quantity represented by the expression or equation.');

insert into math_comp_map (class_id, description)
values ('cmath16-10025','Simplify basic expressions with integer exponents (i.e. basic laws of exponents). Simplify simple rational and radical expressions (limited to square roots).');

insert into math_comp_map (class_id, description)
values ('cmath16-10026','Find and simplify basic intersections and unions of sets and intervals and express the results using appropriate notation, including roster notation, set-builder notation, and interval notation.');

insert into math_comp_map (class_id, description)
values ('cmath16-10027','Use the structure of an expression (including expressions as part of equations and inequalities) to identify ways to simplify and rewrite it.');

insert into math_comp_map (class_id, description)
values ('cmath16-10028','Rewrite logarithmic expressions as exponential expressions and exponential expressions as logarithmic expressions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10029','Understand and use the properties of logarithms to simplify logarithmic numeric expressions and to identify their approximate value.');

insert into math_comp_map (class_id, description)
values ('cmath16-10030','Understand the inverse relationship between exponents and logarithms and use this relationship to solve problems involving logarithms and exponents.');

insert into math_comp_map (class_id, description)
values ('cmath16-10031','For exponential models, express as a logarithm the solution to ab^(ct) = d, where a, c, and d are numbers and the base b is 2, 10, e, or other simple expressions; evaluate the logarithm using technology.');

insert into math_comp_map (class_id, description)
values ('cmath16-10032','Evaluate trigonometric expressions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10033','Manipulate trigonometric identities involving all six trigonometric functions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10034','Solve linear equations and linear inequalities in one variable.');

insert into math_comp_map (class_id, description)
values ('cmath16-10035','Use variables to represent quantities in a contextual or non-contextual problem, and construct simple equations to solve problems by reasoning about the quantities.');

insert into math_comp_map (class_id, description)
values ('cmath16-10036','Solve basic literal equations in one variable (one copy of the variable being isolated). Include evaluation of formulas for a specific variable.');

insert into math_comp_map (class_id, description)
values ('cmath16-10037','Solve compound inequalities in one variable.');

insert into math_comp_map (class_id, description)
values ('cmath16-10038','Solve literal equations that require factoring (two copies of the variable being isolated).');

insert into math_comp_map (class_id, description)
values ('cmath16-10039','Solve contextual problems involving equations and inequalities in one variable. Include equations arising from linear functions.');

insert into math_comp_map (class_id, description)
values ('cmath16-10040','Use the equation of a linear model to solve problems in the context of bivariate measurement data, interpreting the slope and intercept, and the contextual meanings of these values.');

insert into math_comp_map (class_id, description)
values ('cmath16-10041','Solve equations in one variable that are quadratic and quadratic in form.');

insert into math_comp_map (class_id, description)
values ('cmath16-10042','Solve contextual problems involving given expressions and equations that are: Simple quadratic; Rational, involving proportions (one quantity); Rational, involving variation.');

insert into math_comp_map (class_id, description)
values ('cmath16-10043','Solve absolute value inequalities and other nonlinear inequalities (quadratic, rational) to determine the solution set.');

insert into math_comp_map (class_id, description)
values ('cmath16-10044','Solve equations in one variable by factoring and by other methods, and recognize how extraneous solutions may arise.');

insert into math_comp_map (class_id, description)
values ('cmath16-10045','Use the quadratic formula to solve an equation that results in non-real solutions, and write solutions as a ± bi  for real numbers a and b.');

insert into math_comp_map (class_id, description)
values ('cmath16-10046','Solve contextual problems involving expressions and equations that are: Rational; Radical; Quadratic; Exponential and logarithmic.');

insert into math_comp_map (class_id, description)
values ('cmath16-10047','Solve problems involving polynomial equations of degree three or four with technology.');

insert into math_comp_map (class_id, description)
values ('cmath16-10048','Solve contextual and non-contextual problems involving trigonometric equations with or without technology. Include equations arising from any of the six trigonometric functions (not including inverse functions).');

insert into math_comp_map (class_id, description)
values ('cmath16-10049','Use inverse functions to solve trigonometric equations that arise in modeling contexts.');

insert into math_comp_map (class_id, description)
values ('cmath16-10050','Analyze and solve pairs of simultaneous linear equations.');

insert into math_comp_map (class_id, description)
values ('cmath16-10051','Write two linear equations in two variables, given a verbal description of a context.');

insert into math_comp_map (class_id, description)
values ('cmath16-10052','Interpret coefficients and variables within given linear equations in terms of the context.');

insert into math_comp_map (class_id, description)
values ('cmath16-10053','Analyze and solve contextual problems involving 2x2 linear systems.');

insert into math_comp_map (class_id, description)
values ('cmath16-10054','Solve simple 3x3 systems of linear equations.');

insert into math_comp_map (class_id, description)
values ('cmath16-10055','Analyze and solve simple contextual problems involving 3x3 linear systems.');

insert into math_comp_map (class_id, description)
values ('cmath16-10056','Solve a simple system consisting of a linear equation and a quadratic equation in two variables algebraically and graphically.');

insert into math_comp_map (class_id, description)
values ('cmath16-10057','Solve contextual problems by evaluating given formulas for specific variables, with attention to proper units. (Area, Perimeter)');

insert into math_comp_map (class_id, description)
values ('cmath16-10058','Solve contextual problems by evaluating given formulas for specific variables, with attention to proper units. (Volume, Surface Area, Nets)');

insert into math_comp_map (class_id, description)
values ('cmath16-10059','Apply the Pythagorean Theorem in contextual and non-contextual problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-10060','Apply models and formulas to solve simple design problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-20001','Distinguish between relations and functions, identifying when a relation is a function. Understand that a function is a rule that assigns to each input exactly one output, and that the graph of a function is the set of ordered pairs consisting of an input and the corresponding output.');

insert into math_comp_map (class_id, description)
values ('cmath16-20002','Understand that a function from one set (called the domain) to another set (called the range) assigns to each element of the domain exactly one element of the range.');

insert into math_comp_map (class_id, description)
values ('cmath16-20003','Relate the domain of a function to its graph and, where applicable, to the quantitative relationship it describes.');

insert into math_comp_map (class_id, description)
values ('cmath16-20004','Given two functions each represented in a different way, justify or refute the existence of a relationship between the two functions (limited to combinations of linear and quadratic models and functions).');

insert into math_comp_map (class_id, description)
values ('cmath16-20005','Distinguish between situations that can be modeled with linear functions and with exponential functions.');

insert into math_comp_map (class_id, description)
values ('cmath16-20006','Recognize and represent functions given verbally, numerically, graphically and algebraically.');

insert into math_comp_map (class_id, description)
values ('cmath16-20007','Compare properties of two functions each represented in a different way (algebraically, graphically, numerically in tables, or by verbal descriptions).');

insert into math_comp_map (class_id, description)
values ('cmath16-20008','Interpret the parameters in a linear or simple exponential function in terms of a context.');

insert into math_comp_map (class_id, description)
values ('cmath16-20009','Given the graph of a function that models a relationship between two quantities, identify the type of function represented by interpreting key features of graphs.');

insert into math_comp_map (class_id, description)
values ('cmath16-20010','Use function notation, evaluate functions for inputs in their domains, and interpret statements that use function notation in terms of a context.');

insert into math_comp_map (class_id, description)
values ('cmath16-20011','Describe the effect that a change in the value of one variable has on the value(s) of other variables in a nonlinear algebraic relationship.');

insert into math_comp_map (class_id, description)
values ('cmath16-20012','Determine whether the solutions of problems involving linear, quadratic, polynomial, root/radical/power, exponential, logarithmic, rational, and piecewise-defined functions are reasonable. Interpret these solutions in context as appropriate.');

insert into math_comp_map (class_id, description)
values ('cmath16-20013','Determine whether the solutions of problems involving trigonometric functions are reasonable. Interpret these solutions in context as appropriate.');

insert into math_comp_map (class_id, description)
values ('cmath16-20014','For a function that models a relationship between two quantities, interpret key features of graphs in terms of the quantities, and select graphs that match verbal descriptions showing key features of the relationship.');

insert into math_comp_map (class_id, description)
values ('cmath16-20015','Solve basic rate and ratio problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-20016','Solve non-contextual problems involving simple proportions (single copy of the variable being sought).');

insert into math_comp_map (class_id, description)
values ('cmath16-20017','Use proportional relationships to solve multistep ratio and percent problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-20018','Solve proportion problems involving algebraic expressions.');

insert into math_comp_map (class_id, description)
values ('cmath16-20019','Use proportional relationships to solve multistep ratio and percent problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-30001','Recognize opposite signs of numbers as indicating locations on opposite sides of 0 on the number line; recognize that the opposite of the opposite of a number is the number itself.');

insert into math_comp_map (class_id, description)
values ('cmath16-30002','Find and position integers and other rational numbers on a vertical or horizontal number line diagram.');

insert into math_comp_map (class_id, description)
values ('cmath16-30003','Graph simple inequalities in one variable on the number line. Represent inequalities containing > and < symbols with open circles, and inequalities containing ≥ and ≤ symbols with closed circles.');

insert into math_comp_map (class_id, description)
values ('cmath16-30004','Use a pair of perpendicular number lines, called axes, to define a coordinate system, with the intersection of the lines (the origin) arranged to coincide with the 0 on each line and a given point in the plane located by using an ordered pair of numbers, called its coordinates. Understand that the first number indicates how far to travel from the origin in the direction of one axis, and the second number indicates how far to travel in the direction of the second axis, with the convention that the names of the two axes and the coordinates correspond.');

insert into math_comp_map (class_id, description)
values ('cmath16-30005','Represent contextual and non-contextual problems by graphing points on the coordinate plane (using an appropriate scale), and interpret coordinate values of points in the context of the situation.');

insert into math_comp_map (class_id, description)
values ('cmath16-30006','Graph functions expressed symbolically and show key features of the graph. (Linear functions and inequalities)');

insert into math_comp_map (class_id, description)
values ('cmath16-30007','Analyze and solve 2x2 systems of linear inequalities. Understand that solutions to a system of two linear inequalities in two variables correspond to the regions of intersection of their graphs, because regions of intersection satisfy both inequalities simultaneously.');

insert into math_comp_map (class_id, description)
values ('cmath16-30008','Graph functions expressed symbolically and show key features of the graph. (Quadratic, square root, cube root, piecewise, polynomial)');

insert into math_comp_map (class_id, description)
values ('cmath16-30009','Graph exponential and logarithmic functions, showing intercepts, end behavior, and asymptotes.');

insert into math_comp_map (class_id, description)
values ('cmath16-30010','Identify the effect on the graph of replacing f(x)by f(x) + k, kf(x), and f(x + k) for specific values of k (both positive and negative); find the value of k given the graphs.');

insert into math_comp_map (class_id, description)
values ('cmath16-30011','Given the graph of a one-to-one function, construct the graph of its inverse.');

insert into math_comp_map (class_id, description)
values ('cmath16-30012','Given the graph of a function that is not one-to-one, construct the graph of an inverse function.');

insert into math_comp_map (class_id, description)
values ('cmath16-30013','Given a linear equation, determine whether a given ordered pair is a solution of the equation.');

insert into math_comp_map (class_id, description)
values ('cmath16-30014','Understand that the graph of an equation in two variables is the set of its solutions plotted in the coordinate plane.');

insert into math_comp_map (class_id, description)
values ('cmath16-30015','Given a linear inequality, determine whether a given ordered pair is part of the solution set.');

insert into math_comp_map (class_id, description)
values ('cmath16-30016','Identify that a line described by an  equation y = mx passes through the origin and that a line described by an equation y = mx + b intercepts the vertical axis at b.');

insert into math_comp_map (class_id, description)
values ('cmath16-30017','Interpret the slope (rate of change) and the intercept (constant term) of a given linear model in the context of the data.');

insert into math_comp_map (class_id, description)
values ('cmath16-40001','Read and write multi-digit whole numbers using base-ten numerals, number names, and expanded form. Compare two multi-digit numbers based on meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons.');

insert into math_comp_map (class_id, description)
values ('cmath16-40002','Use place value understanding to round numbers to any place.');

insert into math_comp_map (class_id, description)
values ('cmath16-40003','Read and write decimals to thousandths using base-ten numerals, number names, and expanded form.');

insert into math_comp_map (class_id, description)
values ('cmath16-40004','Read, write, and compare decimals to thousandths. Compare two decimals to thousandths based on meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons.');

insert into math_comp_map (class_id, description)
values ('cmath16-40005','Identify patterns in the number of zeros of the product when multiplying a number by powers of 10, and explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10. Convert between scientific notation and decimal notation.');

insert into math_comp_map (class_id, description)
values ('cmath16-40006','Perform operations with numbers expressed in scientific notation, using only positive exponents, including problems where both decimal and scientific notation are used. Interpret scientific notation that has been generated by technology.');

insert into math_comp_map (class_id, description)
values ('cmath16-40007','Perform operations with numbers expressed in scientific notation, using both positive and negative exponents, including problems where both decimal and scientific notation are used. Use scientific notation and choose units of appropriate size for measurements of very large or very small quantities.');

insert into math_comp_map (class_id, description)
values ('cmath16-40008','Explain equivalence of fractions in special cases, and compare fractions by reasoning about their size.');

insert into math_comp_map (class_id, description)
values ('cmath16-40009','Compare two fractions, using >, =, and < symbols to record the results of comparisons.');

insert into math_comp_map (class_id, description)
values ('cmath16-40010','Use decimal notation for fractions with denominators 10, 100, or 1,000.');

insert into math_comp_map (class_id, description)
values ('cmath16-40011','Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions in such a way as to produce an equivalent sum or difference of fractions with like denominators.');

insert into math_comp_map (class_id, description)
values ('cmath16-40012','Solve simple non-contextual problems involving whole numbers, fractions, decimals, and percents without technology.');

insert into math_comp_map (class_id, description)
values ('cmath16-40013','Determine whether a given whole number is prime or composite. Express a composite number as factors a product of its prime.');

insert into math_comp_map (class_id, description)
values ('cmath16-40014','Determine the greatest common factor (GCF) and the least common multiple (LCM) of whole numbers.');

insert into math_comp_map (class_id, description)
values ('cmath16-40015','Apply and extend previous understandings of multiplication and division and of fractions to multiply, divide, and exponentiate rational numbers.');

insert into math_comp_map (class_id, description)
values ('cmath16-40016','Solve non-contextual problems involving the four operations with non-negative rational numbers.');

insert into math_comp_map (class_id, description)
values ('cmath16-40017','Find a percent of a quantity as a rate per 100.');

insert into math_comp_map (class_id, description)
values ('cmath16-40018','Solve problems involving finding the whole, given a part and the percent and problems involving finding the part, given a percent and the whole.');

insert into math_comp_map (class_id, description)
values ('cmath16-40019','Estimate to solve contextual problems. Assess the reasonableness of answers using mental computation and strategies including rounding.');

insert into math_comp_map (class_id, description)
values ('cmath16-40020','Solve non-contextual problems involving the four operations with rational numbers. Describe situations in which opposite quantities combine to make 0.');

insert into math_comp_map (class_id, description)
values ('cmath16-50001','Use facts about supplementary, complementary, vertical, and corresponding angles to solve problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-50002','Use similarity criteria for polygons to solve problems.');

insert into math_comp_map (class_id, description)
values ('cmath16-50003','Use trigonometric ratios to solve right triangles in applied problems, including using trigonometric ratios for special right triangles.');

insert into math_comp_map (class_id, description)
values ('cmath16-60001','Interpret conditional statements.');

