-- Autogenerated sql created by jasonbrown on: 02/15/2016

insert into english_comp_map (class_id, description)
values ('ceng_16-10001','Demonstrate understanding of words and phrases acquired through conversations, reading authentic texts, and being read to.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10002','Demonstrate understanding of general academic language from authentic business and mass media sources.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10003','Demonstrate understanding of general academic and technical words and phrases; gather vocabulary knowledge when considering a word or phrase important to comprehension or expression.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10004','Demonstrate a nuanced understanding of general academic, technical, and domain- specific words and phrases, sufficient for reading and writing at the college and career readiness level; demonstrate independence in gathering vocabulary knowledge when considering a word or phrase important to comprehension or expression');

insert into english_comp_map (class_id, description)
values ('ceng_16-10005','Recognize variations from standard English in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10006','Differentiate between slang, idioms, and standard English in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10007','Compare and contrast the varieties of English (e.g., dialects, registers) used in expository or academic fiction or non-fiction texts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10008','Analyze the varieties of English (e.g., dialects, registers) used in expository or academic fiction or non-fiction texts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10009','Demonstrate understanding of a basic multistep procedure.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10010','Demonstrate understanding of a multistep procedure.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10011','Demonstrate understanding of a complex multistep procedure.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10012','Demonstrate understanding of a highly complex multistep procedure.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10013','Describe the relationship between a series of events, ideas, concepts, or procedures in an authentic text, using language that pertains to time, sequence, and cause/effect.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10014','Explain literal and implied relationships between events, procedures, ideas, or concepts based on specific information in an authentic text, including predicting what will happen next.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10015','Analyze how an expository or academic fiction or nonfiction text makes literal and implied connections among and distinctions between individuals, ideas, or events (e.g., through comparisons, analogies, allusions, or categories).');

insert into english_comp_map (class_id, description)
values ('ceng_16-10016','Analyze a complex set of literal or implied ideas or sequences of events and explain how specific individuals, ideas, or events interact and develop over the course of an expository or academic fiction or nonfiction text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10017','Determine the main idea of an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10018','Determine the literal and implied main idea of an authentic text and how it is supported by key details.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10019','Determine the literal and implied main idea, theme, or conclusions of an expository or academic fiction or non-fiction text and how it is supported by key details.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10020','Determine the literal and implied main idea, theme, or conclusions of an expository or academic fiction or non-fiction text and analyze in detail its development over the course of the text, including how it emerges and is shaped and refined by specific details.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10021','Write a one-sentence summary.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10022','Outline the main idea and key details of an authentic text. Demonstrate comprehension by using a graphic organizer to map content in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10023','Write a paragraph summary of an expository or academic fiction or non-fiction text that is separate from personal opinions or judgments.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10024','Write an accurate summary of an expository or academic fiction or non-fiction text that includes complex concepts, processes, or information and is free of personal opinions or judgments. Evaluate the accuracy of a summary of an expository or academic fiction or non-fiction text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10025','Identify the main purpose of an authentic text, including what the author wants to answer, explain, or describe.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10026','Identify purpose and stance in multiple accounts of the same event or topic in authentic texts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10027','Determine an author’s purpose and stance in an expository or academic fiction or nonfiction text and recognize how the author acknowledges and responds to conflicting evidence or viewpoints. Identify examples from an expository or academic fiction or nonfiction text that reveal an author’s purpose and stance.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10028','Determine an author’s purpose and stance in an expository or academic fiction or nonfiction text and analyze how an author advances that purpose and stance and responds to conflicting evidence or viewpoints. Identify and analyze aspects of an expository or academic fiction or nonfiction text that reveal an author’s tone, purpose, or stance (e.g., loaded language, inclusion or avoidance of particular facts, figurative language).');

insert into english_comp_map (class_id, description)
values ('ceng_16-10029','Identify an author’s stance in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10030','Distinguish own stance from that of the author of an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10031','Compare the stance of two or more authors for how they treat the same or similar topics in an expository or academic fiction or nonfiction text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10032','Analyze and evaluate the stance of two or more authors for how they treat the same or similar topics in an expository or academic fiction or nonfiction text, including which details they include and emphasize in their respective accounts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10033','Identify and differentiate between facts and opinions in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10034','Identify and differentiate between facts and opinions in authentic text; identify how the author uses facts to support the conclusion.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10035','Delineate and evaluate clear arguments and specific claims in an expository or academic fiction or nonfiction text; differentiate fact and opinion; follow the line of reasoning to its conclusion.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10036','Delineate and evaluate the argument and specific claims in expository or academic fiction or nonfiction text, assessing whether the reasoning is sound and the evidence is relevant and sufficient; recognize when irrelevant evidence or bias is introduced.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10037','Use various text features (e.g., captions, bold print, subheadings, glossaries, indexes, electronic menus, icons) to locate key facts or information in an authentic text. Use text features and search tools (e.g., key words, sidebars, hyperlinks) to locate information relevant to a given topic.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10038','Describe the overall structure (e.g., chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10039','Analyze how a particular literary or rhetorical element fits into the overall structure of a text and contributes to the development of the ideas. Compare and contrast the overall structure (e.g., chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in two or more expository or academic fiction or nonfiction texts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-10040','Analyze in detail how an author’s ideas or claims are developed and refined by particular sentences, paragraphs, and larger portions of an expository or academic fiction or nonfiction text. Analyze and evaluate the effectiveness of the structure an author uses in his or her exposition or argument, including whether the structure makes the points clear, convincing, and engaging.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20001','List the main points of an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20002','List the main points of an authentic text and identify the author’s conclusion.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20003','Demonstrate the ability to summarize, analyze, and make a simple synthesis between two expository or academic fiction or non-fiction texts.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20004','Conduct purpose-driven research projects to answer a question or solve a problem; narrow or broaden the inquiry when appropriate; synthesize multiple sources on the subject, demonstrating understanding of the subject under investigation.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20005','Express an opinion about an idea found in an authentic text and give reasons (e.g., agree or disagree with the death penalty in response to a short news item on capital punishment and give reasons based on personal beliefs).');

insert into english_comp_map (class_id, description)
values ('ceng_16-20006','Establish a claim based on details and examples in an authentic text (e.g., list reasons for agreement or disagreement with the death penalty based on a short news item on capital punishment).');

insert into english_comp_map (class_id, description)
values ('ceng_16-20007','Establish a claim and cite evidence from an expository or academic fiction or non-fiction text (e.g., state a position on the death penalty based on an academic text on capital punishment and support this stance with evidence).');

insert into english_comp_map (class_id, description)
values ('ceng_16-20008','Establish an original argument with reasons backed by evidence from an expository or academic fiction or non-fiction text (e.g., argue for or against the efficacy of the death penalty based on an academic text on capital punishment).');

insert into english_comp_map (class_id, description)
values ('ceng_16-20009','Locate information in an authentic print or digital source.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20010','Locate and organize information from personal experiences or authentic print and digital sources; take brief notes on sources.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20011','Gather relevant information from personal experience and a print or digital academic source; assess the relevance and reliability of the source; quote the source while avoiding plagiarism.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20012','Gather relevant information from primary and secondary print and digital academic sources, using search terms effectively; assess the credibility and accuracy of each source; quote or paraphrase the data and conclusions of others while avoiding plagiarism and following a standard format for citation.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20013','Recognize a direct quote in an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20014','Quote accurately from an authentic text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20015','Quote accurately from an expository or academic fiction or non-fiction text.');

insert into english_comp_map (class_id, description)
values ('ceng_16-20016','Quote and paraphrase appropriately and accurately from an expository or academic fiction or non-fiction text to effectively support a claim.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30001','Demonstrate familiarity with standard English and basic syntax when writing: Write complete simple sentences Identify simple, compound, and complex sentences Employ proper subject/verb agreement Distinguish between adjective and adverb word forms Employ proper pronoun agreement');

insert into english_comp_map (class_id, description)
values ('ceng_16-30002','Demonstrate basic understanding of the general conventions of standard English grammar and usage when writing: Write simple and compound sentences Use phrases and clauses Identify prepositional phrases Recognize and correct subject/verb agreement errors in simple sentences Form and use appropriate verb tenses including progressive, simple present, simple past, and future Recognize and correct pronoun case errors Correctly use frequently confused words (e.g., to, too, two; there, their, they’re)');

insert into english_comp_map (class_id, description)
values ('ceng_16-30003','Demonstrate proficiency with the general conventions of standard English grammar and usage when writing: Choose among simple and compound sentences to signal differing relationships among ideas Subordinate phrases and clauses to indicate connections between ideas Place phrases and clauses within a sentence, recognizing and correcting misplaced and dangling modifiers Recognize and correct run-ons and fragments Recognize and correct subject/verb agreement errors in complex sentences Form and use verbals (gerunds, participles, infinitives) Form and use modal auxiliaries and appropriate verb tenses including progressive, present, past, and perfect tenses Use the appropriate order of multiple adjectives (e.g., opinion, size, color, texture, material) Correct shifts in pronoun number and case as well as unclear pronoun reference Correctly use frequently confused words (e.g., except, accept; then, than) Demonstrate an awareness of gender-neutral language');

insert into english_comp_map (class_id, description)
values ('ceng_16-30004','Demonstrate command of the general conventions of standard English grammar and usage when writing: Use parallel structure Use various types of phrases (noun, verb, adjectival, adverbial, participial, prepositional, absolute) and clauses (independent, dependent; noun, relative, adverbial) to convey specific meanings and add variety and interest to writing or presentations Use gender-neutral language');

insert into english_comp_map (class_id, description)
values ('ceng_16-30005','Demonstrate the basic conventions of standard English capitalization, punctuation, and spelling when writing a simple sentence.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30006','Demonstrate basic understanding of the conventions of standard English capitalization, punctuation, and spelling when writing essays.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30007','Demonstrate proficiency with the conventions of standard English capitalization, punctuation, and spelling when writing essays.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30008','Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing essays.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30009','Use standard English words and phrases with few errors that obscure meaning.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30010','Choose conventional language that adequately expresses ideas, recognizing and reducing wordiness.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30011','Choose language that effectively expresses ideas, recognizing and eliminating wordiness.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30012','Choose language that effectively expresses ideas precisely and concisely, recognizing and eliminating wordiness.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30013','Determine or clarify the meaning of unknown and multiple-meaning words and phrases in authentic texts, choosing flexibly from an array of strategies: Use sentence-level context as a clue to the meaning of a word or phrase Determine the meaning of the new word formed when a known prefix is added to a known word (e.g., happy/unhappy, tell/retell) Use a known root word as a clue to the meaning of an unknown word with the same root (e.g., addition, additional) Use knowledge of the meaning of individual words to predict the meaning of compound words (e.g., birdhouse, lighthouse, housefly; bookshelf, notebook, bookmark)');

insert into english_comp_map (class_id, description)
values ('ceng_16-30014','Determine or clarify the meaning of unknown and multiple-meaning words or phrases in authentic print and digital sources. Use context (e.g., the overall meaning of a sentence or paragraph; a words position or function in a sentence) as a clue to the meaning of a word or phrase. Use common affixes and roots as clues to the meaning of a word (e.g., pro- and anti-).');

insert into english_comp_map (class_id, description)
values ('ceng_16-30015','Determine or clarify the meaning of unknown and multiple-meaning words or phrases in an expository or academic fiction or nonfiction text.  Use context (e.g., the overall meaning of a sentence or paragraph; a words position or function in a sentence) as a clue to the meaning of a word or phrase.  Use common affixes and roots as clues to the meaning of a word (e.g., precede, recede, secede).');

insert into english_comp_map (class_id, description)
values ('ceng_16-30016','Determine or clarify the meaning of unknown and multiple-meaning words, homophones, and phrases in an expository or academic fiction or nonfiction text.  Demonstrate an understanding of patterns of word changes that indicate different meanings or parts of speech (e.g., analyze, analysis, analytical; advocate, advocacy) and apply knowledge of roots and affixes.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30017','Choose the appropriate definition among multiple definitions in a dictionary of common words with clear differences between meanings.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30018','Verify the preliminary determination of the meaning or part of speech of a word or phrase (e.g., dictionaries, glossaries, thesauruses).  Choose the appropriate definition among multiple definitions in a dictionary of words with nuanced differences in meaning.');

insert into english_comp_map (class_id, description)
values ('ceng_16-30019','Consult general and specialized reference materials (e.g., dictionaries, glossaries, thesauruses, or discipline-specific references), both print and digital, determine or clarify a word’s precise meaning, part of speech, or etymology.  Choose the appropriate definition among multiple definitions in a dictionary of academic words with nuanced differences in meaning.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40001','Write simple, assignment-driven informative or explanatory paragraphs or short papers that examine a topic and convey ideas.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40002','Write assignment-driven informative or explanatory paragraphs or short essays that examine a topic and convey ideas and information clearly.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40003','Write informative or explanatory texts to examine a topic and adequately convey ideas, concepts, and information through the selection, organization, and analysis of relevant content.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40004','Write informative or explanatory texts to examine and convey complex ideas, concepts, and information clearly and accurately through the effective selection, organization, and analysis of content, including narration, explanation, and process analysis.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40005','Respond to a timed writing prompt.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40006','Develop a plan and write a complete response to a timed prompt.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40007','Strategize and execute a plan in response to a timed writing prompt.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40008','Effectively strategize and execute a plan that responds thoroughly to a timed writing prompt.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40009','State a simple topic.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40010','State a specific main idea.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40011','Create a developed, specific main idea that is relevant to the assignment and supportable.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40012','Create a fully developed, specific central claim that is relevant to the assignment, arguable, and defensible.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40013','Group information related to a topic.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40014','Use details to support a main idea; differentiate between examples and general statements.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40015','Develop the main idea with relevant facts, definitions, concrete details, quotations, or other information and examples.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40016','Develop the central claim and build to a logical conclusion with well-chosen, relevant, and sufficient facts, extended definitions, concrete details, quotations, or other information and examples appropriate to communicate clearly to the audience.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40017','Identify appropriate personal experiences, examples, or details relevant to the topic.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40018','Use appropriate personal experiences, examples, or a text as evidence.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40019','Draw evidence from a variety of texts to support a main idea.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40020','Draw relevant evidence from a variety of texts to support analysis, reflection, and argument.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40021','Introduce a topic and organize a paragraph by grouping examples and making connections between ideas.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40022','Introduce a topic and organize a paragraph that captures ideas, concepts, and information and that communicates basic relationships by using a topic sentence and details that support the central idea.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40023','Introduce a topic and organize an essay that captures ideas, concepts, and information and communicates logical relationships by using topic sentences and paragraphs to support the central idea. Introduce a topic clearly and organize ideas, concepts, and information using a designated rhetorical mode.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40024','Introduce a topic and organize an essay that captures complex ideas, concepts, and information and communicates logical relationships by effectively arranging topic sentences and paragraphs to support the central claim. Refine, qualify, and amplify the thesis, and determine and use the appropriate rhetorical mode.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40025','Produce writing that demonstrates a basic awareness of purpose and audience.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40026','Produce writing that demonstrates understanding of how purpose and audience affect writing.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40027','Produce clear and coherent writing in which the development, organization, and style are adequate to task, purpose, and audience.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40028','Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience; establish and maintain an academic voice.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40029','Recognize and imitate basic sentence models.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40030','Differentiate and use a variety of sentence types.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40031','Vary sentence patterns for meaning, reader interest, and style.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40032','Vary syntax for effect, consulting references for guidance as needed.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40033','Develop and strengthen writing by responding to comments on the writing.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40034','Develop and strengthen writing by planning, revising, editing, rewriting, or trying a new approach in response to comments on the writing.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40035','Develop and strengthen writing by planning, revising, editing, rewriting, or trying a new approach, focusing on how well purpose and audience have been addressed in response to global comments on the writing.');

insert into english_comp_map (class_id, description)
values ('ceng_16-40036','Develop and strengthen writing independently by planning, revising, editing, rewriting, or trying a new approach, focusing on addressing what is most significant for a specific purpose and audience. Write and edit work so that it conforms to the guidelines in a style manual appropriate for the discipline and writing type.');

