UPDATE district SET name = 'Allan Hancock' WHERE ccc_id ='610';
UPDATE district SET name = 'Antelope Valley' WHERE ccc_id ='620';
UPDATE district SET name = 'Cabrillo' WHERE ccc_id ='410';
UPDATE district SET name = 'Citrus' WHERE ccc_id ='820';
UPDATE district SET name = 'Chabot-Las Positas' WHERE ccc_id ='480';
UPDATE district SET name = 'Compton' WHERE ccc_id ='710';
UPDATE district SET name = 'El Camino' WHERE ccc_id ='720';
UPDATE district SET name = 'Feather River' WHERE ccc_id ='120';
UPDATE district SET name = 'Gavilan' WHERE ccc_id ='440';
UPDATE district SET name = 'Foothill-Deanza' WHERE ccc_id ='420';
UPDATE district SET name = 'Glendale' WHERE ccc_id ='730';
UPDATE district SET name = 'Hartnell' WHERE ccc_id ='450';
UPDATE district SET name = 'Grossmont-Cuyamaca' WHERE ccc_id ='20';
UPDATE district SET name = 'Imperial' WHERE ccc_id ='30';
UPDATE district SET name = 'Kern' WHERE ccc_id ='520';
UPDATE district SET name = 'Lake Tahoe' WHERE ccc_id ='220';
UPDATE district SET name = 'Lassen' WHERE ccc_id ='130';
UPDATE district SET name = 'Mendocino-Lakev' WHERE ccc_id ='140';
UPDATE district SET name = 'Los Rios' WHERE ccc_id ='230';
UPDATE district SET name = 'Marin' WHERE ccc_id ='330';
UPDATE district SET name = 'Merced' WHERE ccc_id ='530';
UPDATE district SET name = 'Mira Costa' WHERE ccc_id ='50';
UPDATE district SET name = 'Monterey' WHERE ccc_id ='460';
UPDATE district SET name = 'Napa Valley' WHERE ccc_id ='240';
UPDATE district SET name = 'Ohlone' WHERE ccc_id ='430';
UPDATE district SET name = 'Palmoar' WHERE ccc_id ='60';
UPDATE district SET name = 'Pasadena' WHERE ccc_id ='770';
UPDATE district SET name = 'Redwoods' WHERE ccc_id ='160';
UPDATE district SET name = 'Peralta' WHERE ccc_id ='340';
UPDATE district SET name = 'San Joaquin Delta' WHERE ccc_id ='550';
UPDATE district SET name = 'San Diego' WHERE ccc_id ='70';
UPDATE district SET name = 'San Francisco' WHERE ccc_id ='360';
UPDATE district SET name = 'San Luis Obispo' WHERE ccc_id ='640';
UPDATE district SET name = 'San Jose-Evergreen' WHERE ccc_id ='470';
UPDATE district SET name = 'San Mateo' WHERE ccc_id ='370';
UPDATE district SET name = 'Santa Clarita' WHERE ccc_id ='660';
UPDATE district SET name = 'Santa Barbara' WHERE ccc_id ='650';
UPDATE district SET name = 'Santa Monica' WHERE ccc_id ='780';
UPDATE district SET name = 'Sequoias' WHERE ccc_id ='560';
UPDATE district SET name = 'Shasta-Tehama-Trinity' WHERE ccc_id ='170';
UPDATE district SET name = 'Sierra' WHERE ccc_id ='270';
UPDATE district SET name = 'Siskiyous' WHERE ccc_id ='180';
UPDATE district SET name = 'Solano' WHERE ccc_id ='280';
UPDATE district SET name = 'Sonoma' WHERE ccc_id ='260';
UPDATE district SET name = 'Southwestern' WHERE ccc_id ='90';
UPDATE district SET name = 'Ventura' WHERE ccc_id ='680';
UPDATE district SET name = 'State Center' WHERE ccc_id ='570';
UPDATE district SET name = 'West Kern' WHERE ccc_id ='690';
UPDATE district SET name = 'West Hills' WHERE ccc_id ='580';
UPDATE district SET name = 'Los Angeles Community College' WHERE ccc_id ='740';
UPDATE district SET name = 'West Valley-Mission' WHERE ccc_id ='490';
UPDATE district SET name = 'Yosemite' WHERE ccc_id ='590';
UPDATE district SET name = 'Yuba' WHERE ccc_id ='290';
UPDATE district SET name = 'Barstow' WHERE ccc_id ='910';
UPDATE district SET name = 'Butte' WHERE ccc_id ='110';
UPDATE district SET name = 'Cerritos' WHERE ccc_id ='810';
UPDATE district SET name = 'Chaffey' WHERE ccc_id ='920';
UPDATE district SET name = 'Coast' WHERE ccc_id ='830';
UPDATE district SET name = 'Contra Costa' WHERE ccc_id ='310';
UPDATE district SET name = 'Copper Mountain' WHERE ccc_id ='970';
UPDATE district SET name = 'Desert' WHERE ccc_id ='930';
UPDATE district SET name = 'Long Beach' WHERE ccc_id ='840';
UPDATE district SET name = 'Mt. San Antonio' WHERE ccc_id ='850';
UPDATE district SET name = 'Mt. San Jacinto' WHERE ccc_id ='940';
UPDATE district SET name = 'North Orange' WHERE ccc_id ='860';
UPDATE district SET name = 'Palo Verde' WHERE ccc_id ='950';
UPDATE district SET name = 'Rancho Santiago' WHERE ccc_id ='870';
UPDATE district SET name = 'Rio Hondo' WHERE ccc_id ='880';
UPDATE district SET name = 'Riverside' WHERE ccc_id ='960';
UPDATE district SET name = 'San Bernardino' WHERE ccc_id ='980';
UPDATE district SET name = 'South Orange' WHERE ccc_id ='890';
UPDATE district SET name = 'Victor Valley' WHERE ccc_id ='990';
UPDATE district SET name = 'CCCTC Test College District' WHERE ccc_id ='ZZ0';
