-- set users with to-be-removed groups to now be proctors

update user_account_security_group uasg
set security_group_id =
    (select security_group_id from security_group sg where 
sg.group_name='PROCTOR')
where uasg.security_group_id in (
	select security_group_id from security_group sg
    where sg.group_name in ('COUNSELOR', 'FACULTY', 'RESEARCHER', 
	'CONFIGURATOR')
);

-- remove unused security group security permission associations
-- exeplicitily list group names just in case.
delete from security_group_security_permission
	where security_group_id in (
		select security_group_id from security_group
		where group_name in ('STUDENT', 'ADMIN', 'PROCTOR', 'COUNSELOR', 'FACULTY', 'RESEARCHER', 'CONFIGURATOR', 'DEVELOPER', 'PROCESSOR'));

-- remove unused security groups
delete from security_group 
	where group_name in ('COUNSELOR', 'FACULTY', 'RESEARCHER', 'CONFIGURATOR');

-- remove unused permissions
delete from security_permission
	where security_permission_id not in (
		'VIEW_SERVER_CONFIG',
		'VIEW_PROCTOR_DASHBOARD',
		'VIEW_ADMIN_DASHBOARD',
		'VIEW_CODE_VERSION',
		'PRINT_ASSESSMENT_SESSION', 
		'VIEW_ASSESSMENT_SESSION',
		'VIEW_PREVIEW_ASSESSMENT_UPLOAD_UI',
		'VIEW_PROTOTYPE_ASSESSMENT',
		'VIEW_REDACT_ASSESSMENT_UI',
		'VIEW_ACCOMMODATIONS',
		'CREATE_ACTIVATION',
		'CREATE_ACTIVATION_SEARCH_SET',
		'FIND_ACTIVATIONS',
		'DELETE_ACTIVATION_SEARCH_SET',
		'VIEW_ACTIVATION_SEARCH_SET',
		'UPDATE_ACTIVATION_SEARCH_SET',
		'VIEW_CURRENT_USER_ACTIVE_ACTIVATIONS',
		'VIEW_CURRENT_USER_ACTIVATIONS',
		'VIEW_ACTIVATIONS_REPORT',
		'VIEW_ACTIVATION_STATUS_CHANGE_REPORT',
		'VIEW_ACTIVATION',
		'AUTHORIZE_ACTIVATION',
		'CANCEL_ACTIVATION', 
		'LAUNCH_ACTIVATION',
		'PAUSE_ACTIVATION',
		'CREATE_ACTIVITY_LOG_ENTRY',
		'VIEW_ACTIVITY_LOG',
		'VIEW_ASSESSMENT_METADATA',
		'VIEW_ASSESSMENTS', 
		'VIEW_ASSESSMENTS_BY_LOCATION',
		'PUBLISH_ASSESSMENT',
		'PUBLISH_ASSESSMENT_ITEM',
		'VIEW_ASSESSMENT',
		'VIEW_ASSESSMENT_ITEM',
		'VIEW_ALL_ASSESSMENT_SESSIONS', 
		'VIEW_DELIVERY_ASSESSMENT_SESSION',
		'CREATE_ASSESSMENT_SESSION_ACTIVITY_ENTRY',
		'COMPLETE_ASSESSMENT_SESSION_TASK_SET',
 		'UPDATE_ASSESSMENT_SESSION_TASK_SET_RESPONSE',
 		'VIEW_PASSCODES_FOR_CURRENT_USER',
 		'VIEW_PRIVATE_PASSCODE_FOR_CURRENT_USER',
 		'VIEW_PUBLIC_PASSCODE_FOR_CURRENT_USER',
 		'VIEW_PREVIEW_ASSESSMENT_SESSION',
 		'COMPLETE_PREVIEW_ASSESSMENT_SESSION_TASK_SET',
 		'UPDATE_PREVIEW_ASSESSMENT_SESSION_TASK_SET_RESPONSE',
 		'CHECK_PREVIEW_ASSESSMENT_SESSION_TASK_SET_SCORE',
 		'CHECK_PREVIEW_ASSESSMENT_SESSION_TASK_SCORE',
 		'UPLOAD_PREVIEW_ASSESSMENT_PACKAGE',
 		'REDACT_ASSESSMENT_PACKAGE',
 		'DOWNLOAD_RESPONSE_REPORT',
 		'VIEW_ASSESSMENT_SESSIONS_SEQUENCE',
 		'GENERATE_SAMPLE_ASSESSMENT_SESSIONS',
 		'STORE_RESPONSE_REPORT',
 		'DOWNLOAD_STATIC_REPORT',
 		'FIND_STUDENT',
 		'UPLOAD_ASSESSMENT_PACKAGE',
 		'VIEW_TEST_LOCATIONS_BY_USER',
 		'VIEW_STUDENT_DASHBOARD',
 		'UPLOAD_ASSESSMENT_PACKAGE_UI',
 		'VIEW_UPLOADED_ASSESSMENT_PACKAGE',
		'LAUNCH_PAPER_ACTIVATION',
		'VIEW_PROCTOR_ACTIVATION',
		'VIEW_PROCESSOR_DELIVERY_ASSESSMENT_SESSION',
		'TRACK_USER_HISTORY');
