-- new permissions

insert into "security_permission" (security_permission_id, created_on_date, last_updated_date, description) values
	('VIEW_SERVER_CONFIG', timestamp 'now', timestamp 'now', 'View configuration information about the server'),
	('VIEW_PROCTOR_DASHBOARD', timestamp 'now', timestamp 'now', 'View the user''s dashboard'),
	('VIEW_ADMIN_DASHBOARD', timestamp 'now', timestamp 'now', 'View the user''s dashboard'),
	('VIEW_CODE_VERSION', timestamp 'now', timestamp 'now', 'View the version of the codebase and build information'),
	('PRINT_ASSESSMENT_SESSION', timestamp 'now', timestamp 'now', 'Print an assessment session'),
	('VIEW_ASSESSMENT_SESSION', timestamp 'now', timestamp 'now', 'View an assessment session'),
	('VIEW_PREVIEW_ASSESSMENT_UPLOAD_UI', timestamp 'now', timestamp 'now', 'View the assessment preview upload UI'),
	('VIEW_PROTOTYPE_ASSESSMENT', timestamp 'now', timestamp 'now', 'View UX prototypes'),
	('VIEW_REDACT_ASSESSMENT_UI', timestamp 'now', timestamp 'now', 'Upload an assessment and redact its content'),
	('VIEW_ACCOMMODATIONS', timestamp 'now', timestamp 'now', 'Retrieve a list of supported accommodations'),
	('CREATE_ACTIVATION', timestamp 'now', timestamp 'now', 'Create an activation'),
	('CREATE_ACTIVATION_SEARCH_SET', timestamp 'now', timestamp 'now', 'Create a cached set of activation ids'),
	('FIND_ACTIVATIONS', timestamp 'now', timestamp 'now', 'Perform an uncached search'),
	('DELETE_ACTIVATION_SEARCH_SET', timestamp 'now', timestamp 'now', 'Delete an activation search set'),
	('VIEW_ACTIVATION_SEARCH_SET', timestamp 'now', timestamp 'now', 'Perform a cached search of activation ids'),
	('UPDATE_ACTIVATION_SEARCH_SET', timestamp 'now', timestamp 'now', 'Update the activation ids in a cached set'),
	('VIEW_CURRENT_USER_ACTIVE_ACTIVATIONS', timestamp 'now', timestamp 'now', 'View the active activations for the current user'),
	('VIEW_CURRENT_USER_ACTIVATIONS', timestamp 'now', timestamp 'now', 'View all activations for the current user'),
	('VIEW_ACTIVATIONS_REPORT', timestamp 'now', timestamp 'now', 'Generate a CSV report for a specified date range of activations'),
	('VIEW_ACTIVATION_STATUS_CHANGE_REPORT', timestamp 'now', timestamp 'now', 'Generate a report of activation status changes'),
	('VIEW_ACTIVATION', timestamp 'now', timestamp 'now', 'View an activation'),
	('AUTHORIZE_ACTIVATION', timestamp 'now', timestamp 'now', 'Authorize an activation by validating a passcode'),
	('CANCEL_ACTIVATION', timestamp 'now', timestamp 'now', 'Cancel an activation'),
	('LAUNCH_ACTIVATION', timestamp 'now', timestamp 'now', 'Launch an activation'),
	('PAUSE_ACTIVATION', timestamp 'now', timestamp 'now', 'Pause an activation'),
	('CREATE_ACTIVITY_LOG_ENTRY', timestamp 'now', timestamp 'now', 'Create an activity log entry'),
	('VIEW_ACTIVITY_LOG', timestamp 'now', timestamp 'now', 'Generate and view the activity log'),
	('VIEW_ASSESSMENT_METADATA', timestamp 'now', timestamp 'now', 'View an assessment''s metadata'),
	('VIEW_ASSESSMENTS', timestamp 'now', timestamp 'now', 'View a list of unique assessments'),
	('VIEW_ASSESSMENTS_BY_LOCATION', timestamp 'now', timestamp 'now', 'View a list of assessments for a location'),
	('PUBLISH_ASSESSMENT', timestamp 'now', timestamp 'now', 'Mark an assessment as published'),
	('PUBLISH_ASSESSMENT_ITEM', timestamp 'now', timestamp 'now', 'Mark an assessmenet item as published'),
	('VIEW_ASSESSMENT', timestamp 'now', timestamp 'now', 'View an assessment'),
	('VIEW_ASSESSMENT_ITEM', timestamp 'now', timestamp 'now', 'View an assessment item'),
	('VIEW_ALL_ASSESSMENT_SESSIONS', timestamp 'now', timestamp 'now', 'View assessment sessions by user id or session id'),
	('VIEW_DELIVERY_ASSESSMENT_SESSION', timestamp 'now', timestamp 'now', 'View delivery assessment sessions'),
	('CREATE_ASSESSMENT_SESSION_ACTIVITY_ENTRY', timestamp 'now', timestamp 'now', 'Create an activity entry for an assessment session'),
	('COMPLETE_ASSESSMENT_SESSION_TASK_SET', timestamp 'now', timestamp 'now', 'Complete an assessment session'),
	('UPDATE_ASSESSMENT_SESSION_TASK_SET_RESPONSE', timestamp 'now', timestamp 'now', 'Update an assessment session task set response'),
	('VIEW_PASSCODES_FOR_CURRENT_USER', timestamp 'now', timestamp 'now', 'View all passcodes for the current user'),
	('VIEW_PRIVATE_PASSCODE_FOR_CURRENT_USER', timestamp 'now', timestamp 'now', 'View the current user''s private passcode'),
	('VIEW_PUBLIC_PASSCODE_FOR_CURRENT_USER', timestamp 'now', timestamp 'now', 'View the current user''s public passcode'),
	('VIEW_PREVIEW_ASSESSMENT_SESSION', timestamp 'now', timestamp 'now', 'View a preview assessment session'),
	('COMPLETE_PREVIEW_ASSESSMENT_SESSION_TASK_SET', timestamp 'now', timestamp 'now', 'Complete a preview assessment session task set'),
	('UPDATE_PREVIEW_ASSESSMENT_SESSION_TASK_SET_RESPONSE', timestamp 'now', timestamp 'now', 'Update a preview assessment session task set response'),
	('CHECK_PREVIEW_ASSESSMENT_SESSION_TASK_SET_SCORE', timestamp 'now', timestamp 'now', 'Check the score for a preview assessment session task set'),
	('CHECK_PREVIEW_ASSESSMENT_SESSION_TASK_SCORE', timestamp 'now', timestamp 'now', 'Check the score for a preview assessment session task'),
	('UPLOAD_PREVIEW_ASSESSMENT_PACKAGE', timestamp 'now', timestamp 'now', 'Upload a preview assessment package'),
	('REDACT_ASSESSMENT_PACKAGE', timestamp 'now', timestamp 'now', 'Upload and redact an assessment for testing'),
	('DOWNLOAD_RESPONSE_REPORT', timestamp 'now', timestamp 'now', 'Download a response report'),
	('VIEW_ASSESSMENT_SESSIONS_SEQUENCE', timestamp 'now', timestamp 'now', 'View an assessment session sequence'),
	('GENERATE_SAMPLE_ASSESSMENT_SESSIONS', timestamp 'now', timestamp 'now', 'Generate sample assessment sessions'),
	('STORE_RESPONSE_REPORT', timestamp 'now', timestamp 'now', 'Store a response report in S3'),
	('DOWNLOAD_STATIC_REPORT', timestamp 'now', timestamp 'now', 'Download a static, answer key report'),
	('FIND_STUDENT', timestamp 'now', timestamp 'now', 'Search for a student'),
	('UPLOAD_ASSESSMENT_PACKAGE', timestamp 'now', timestamp 'now', 'Upload an assessment package'),
	('VIEW_TEST_LOCATIONS_BY_USER', timestamp 'now', timestamp 'now', 'Get test locations for a user'),
	('VIEW_STUDENT_DASHBOARD', timestamp 'now', timestamp 'now', 'View the user''s dashboard'),
	('UPLOAD_ASSESSMENT_PACKAGE_UI', timestamp 'now', timestamp 'now', 'View the upload assessment package UI'),
	('VIEW_UPLOADED_ASSESSMENT_PACKAGE', timestamp 'now', timestamp 'now', 'View an uploaded assessment package');