package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.util.Date
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:1"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 4.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("1");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_calc_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:2"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("2");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_calc_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:3"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.4 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("3");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:4"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 6) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("4");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:5"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.4 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("5");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:6"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.25) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("6");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:7"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.3) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("7");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:8"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("8");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:9"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.9 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("9");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:10"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("10");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_ge");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:11"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("11");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_stat");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:12"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("12");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_stat");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:13"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.8 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.1) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("13");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_ii");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:14"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.4 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("14");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:15"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("15");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("pre_algebra");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:16"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("16");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("arithmetic");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:17"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.1 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 6) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("17");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_calc_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:18"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.5 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 4.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("18");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_calc_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:19"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("19");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:20"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	algebra_II_cst : Double(this >= 340) from parseFactToDouble((Fact)facts.get("algebra_II_cst"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("20");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:21"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 6.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("21");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:22"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("22");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:23"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.8 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("23");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:24"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("24");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:25"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("25");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:26"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	stat : Double(this >= 2) from parseFactToDouble((Fact)facts.get("stat"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("26");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:27"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3.2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("27");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_ge");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:28"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.9 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
	stat : Double(this >= 2) from parseFactToDouble((Fact)facts.get("stat"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("28");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_ge");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:29"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("29");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_stat");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:30"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("30");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_stat");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:31"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.9 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 1.1) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("31");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_ii");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:32"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.5 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	algebra_II_cst : Double(this >= 302) from parseFactToDouble((Fact)facts.get("algebra_II_cst"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("32");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_ii");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:33"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.5 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("33");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_ii");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:34"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.5 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("34");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:35"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	algebra_II_cst : Double(this >= 302) from parseFactToDouble((Fact)facts.get("algebra_II_cst"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("35");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:36"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.3 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("36");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:37"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 2.1 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("37");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("pre_algebra");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:38"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	cum_gpa :  Double(this >= 1.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
	alg_i_clut_1 : Double(this >= 8) from parseFactToDouble((Fact)facts.get("alg_i_clut_1"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("38");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("pre_algebra");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP Mathematics Decision Logic:8f8a9541-05bb-4589-8cee-813ab5500587:rowname-:rulesetrowid-19819a51-9d9c-45a1-a1d2-807f8e0548ad:rulesetid-null:39"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}") from map.get(RULE_SET_ID_KEY())
	grade : Integer(this ==12) from parseFactToInteger((Fact)facts.get("grade_level"))
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("8f8a9541-05bb-4589-8cee-813ab5500587");
	         placement.setRowNumber("39");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("19819a51-9d9c-45a1-a1d2-807f8e0548ad");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("arithmetic");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end