package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.util.Date
import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.HIGHEST_READING_LEVEL_COURSE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:1"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.5) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("1");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:2"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.5) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("2");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:3"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.3) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("3");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:4"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("4");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:5"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.4) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("5");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:6"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	english : Double(this >= 1.7) from parseFactToDouble((Fact)facts.get("english"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("6");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:7"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.8) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("7");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:8"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("8");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:9"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.7) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("9");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:10"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("10");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:11"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	english : Double(this >= 2.3) from parseFactToDouble((Fact)facts.get("english"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("11");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:12"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("12");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:13"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.6) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("13");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:14"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.4) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("14");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:15"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.5) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("15");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:16"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("E");
	        placement.setLevelsBelowTransfer(5);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("16");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:17"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.8) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("17");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:18"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.3) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("18");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:19"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.8) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("19");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:20"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 11) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(5);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("20");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:21"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.9) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("21");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:22"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cst : Integer(this >= 292) from parseFactToInteger((Fact)facts.get("cst"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("22");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:23"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 2.5) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("23");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:24"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.9) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	english : Double(this >= 2) from parseFactToDouble((Fact)facts.get("english"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("24");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:25"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	cum_gpa : Double(this >= 1.8) from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("25");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Statewide MMAP ESL Decision Logic:5980126b-db8e-47f9-a622-e3809dceda54:rowname-:rulesetrowid-203061a8-e5ce-4a45-b64c-aaae2e8cab20:rulesetid-null:26"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
	grade : Integer(this == 12) from parseFactToInteger((Fact)facts.get("grade_level"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(5);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("5980126b-db8e-47f9-a622-e3809dceda54");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("203061a8-e5ce-4a45-b64c-aaae2e8cab20");
	        placement.setRowNumber("26");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end