package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.util.Date
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToBoolean
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:1"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("preAlgebra"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("algebraI"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("algebraII"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("mathGE"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("statistics"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("collegeAlgebra"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("trigonometry"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("preCalculus"))
	Boolean(this == false )from parseFactToBoolean((Fact)facts.get("calculusI"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("1");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("arithmetic");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:2"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("preAlgebra"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("2");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("pre_algebra");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:3"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("algebraI"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("3");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:4"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("algebraII"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("4");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_alg_ii");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:5"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("mathGE"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("5");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_ge");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:6"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("statistics"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("6");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_stat");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:7"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("collegeAlgebra"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("7");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_col_alg");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:8"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("trigonometry"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("8");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_trig");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:9"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("preCalculus"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("9");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_pre_calc");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math ERP Decision Logic:b0243b06-4b3f-43b8-9cc2-0092360f780d:rowname-:rulesetrowid-446f4075-9c67-4c66-81aa-5f0758d916ae:rulesetid-null:10"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	Boolean(this == true )from parseFactToBoolean((Fact)facts.get("calculusI"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
		List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleId("b0243b06-4b3f-43b8-9cc2-0092360f780d");
	         placement.setRowNumber("10");
	        placement.setTrackingId(trackingId);
	        placement.setRuleSetRowId("446f4075-9c67-4c66-81aa-5f0758d916ae");
	        placement.setCompetencyMapDiscipline("MATH");
	        placement.addProgram("math_calc_i");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	         placement.setDataSourceType(dataSourceType);
	         placement.setStandalonePlacement(true);
	         placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end