package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.util.Date
import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.HIGHEST_READING_LEVEL_COURSE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToBoolean
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:1"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslY_UboundY : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslY_UboundY"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(0);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("1");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:2"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslA_UboundY : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslA_UboundY"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("2");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:3"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslB_UboundY : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslB_UboundY"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("3");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:4"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslA_UboundA : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslA_UboundA"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("A");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("4");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:5"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslB_UboundA : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslB_UboundA"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("5");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:6"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslC_UboundA : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslC_UboundA"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("6");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:7"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslB_UboundB : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslB_UboundB"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("B");
	        placement.setLevelsBelowTransfer(2);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("7");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:8"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslC_UboundB : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslC_UboundB"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("8");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:9"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslD_UboundB : Boolean(this == true )from parseFactToBoolean((Fact)facts.get("eslD_UboundB"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("9");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:10"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslY_UboundY : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslY_UboundY"))
	eslA_UboundY : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslA_UboundY"))
	eslB_UboundY : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslB_UboundY"))
	highestReadingLevel : String(this.equals("0")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("C");
	        placement.setLevelsBelowTransfer(3);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("10");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:11"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslA_UboundA : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslA_UboundA"))
	eslB_UboundA : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslB_UboundA"))
	eslC_UboundA : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslC_UboundA"))
	highestReadingLevel : String(this.equals("1")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("D");
	        placement.setLevelsBelowTransfer(4);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("11");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end
rule "ERP ESL Decision Logic:0e29aaa5-bdb2-46b8-a3b4-3a81de60521a:rowname-:rulesetrowid-1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac:rulesetid-null:12"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslB_UboundB : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslB_UboundB"))
	eslC_UboundB : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslC_UboundB"))
	eslD_UboundB : Boolean(this == false )from parseFactToBoolean((Fact)facts.get("eslD_UboundB"))
	highestReadingLevel : String(this.equals("2")) from  map.get(HIGHEST_READING_LEVEL_COURSE_KEY())
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("E");
	        placement.setLevelsBelowTransfer(5);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("0e29aaa5-bdb2-46b8-a3b4-3a81de60521a");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("1bddd87a-97d0-4ddf-ad3e-85f9f9e5c8ac");
	        placement.setRowNumber("12");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end