/*-------------------------------------------------------------------------------
# Copyright © 2019 by California Community Colleges Chancellor's Office
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#------------------------------------------------------------------------------*/
(function () {

    angular.module('CCC.View.Common').directive('cccTermsOfUse', function () {

        return {

            template: [

                '<ccc-view-manager-static-view page-title="Terms of Use">',
                    '<p><strong>AGREEMENT BETWEEN USER AND Apereo and the party responsible for this sites maintenance of Tesuto</strong></p>',
                    '<p>The Apereo and the party responsible for this sites maintenance of Tesuto Tesuto Web Site (WEBSITE) is comprised of various Web pages operated by Apereo and the party responsible for this sites maintenance of Tesuto.</p>',
                    '<p>The WEBSITE is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein. Your use of the WEBSITE constitutes your agreement to all such terms, conditions, and notices.</p>',
                    '<p><strong>MODIFICATION OF THESE TERMS OF USE</strong></p>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto reserves the right to change the terms, conditions, and notices under which the WEBSITE is offered, including but not limited to the charges associated with the use of the WEBSITE.</p>',
                    '<p><strong>LINKS TO THIRD PARTY SITES</strong></p>',
                    '<p>The WEBSITE may contain links to other Web Sites (&quot;Linked Sites&quot;). The Linked Sites are not under the control of Apereo and the party responsible for this sites maintenance of Tesuto and Apereo and the party responsible for this sites maintenance of Tesuto is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site. Apereo and the party responsible for this sites maintenance of Tesuto is not responsible for webcasting or any other form of transmission received from any Linked Site. Apereo and the party responsible for this sites maintenance of Tesuto is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by Apereo and the party responsible for this sites maintenance of Tesuto of the site or any association with its operators.</p>',
                    '<p><strong>NO UNLAWFUL OR PROHIBITED USE</strong></p>',
                    '<p>As a condition of your use of the WEBSITE, you warrant to Apereo and the party responsible for this sites maintenance of Tesuto that you will not use the WEBSITE for any purpose that is unlawful or prohibited by these terms, conditions, and notices. You may not use the WEBSITE in any manner which could damage, disable, overburden, or impair the WEBSITE or interfere with any other party\'s use and enjoyment of the WEBSITE. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the WEBSITEs.</p>',
                    '<p><strong>USE OF COMMUNICATION SERVICES</strong></p>',
                    '<p>The WEBSITE may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, &quot;Communication Services&quot;), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service. By way of example, and not as a limitation, you agree that when using a Communication Service, you will not:</p>',
                    '<ul>',
                        '<li><p>Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</p></li>',
                        '<li><p>Publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information.</p></li>',
                        '<li><p>Upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents.</p></li>',
                        '<li><p>Upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another\'s computer.</p></li>',
                        '<li><p>Advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages.</p></li>',
                        '<li><p>Conduct or forward surveys, contests, pyramid schemes or chain letters.</p></li>',
                        '<li><p>Download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner. </p></li>',
                        '<li><p>Falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</p></li>',
                        '<li><p>Restrict or inhibit any other user from using and enjoying the Communication Services.</p></li>',
                        '<li><p>Violate any code of conduct or other guidelines which may be applicable for any particular Communication Service.</p></li>',
                        '<li><p>Harvest or otherwise collect information about others, including e-mail addresses, without their consent.</p></li>',
                        '<li><p>Violate any applicable laws or regulations.</p></li>',
                    '</ul>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto has no obligation to monitor the Communication Services. However, Apereo and the party responsible for this sites maintenance of Tesuto reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. Apereo and the party responsible for this sites maintenance of Tesuto reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</p>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in Apereo and the party responsible for this sites maintenance of Tesuto\'s sole discretion.</p>',
                    '<p>Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. Apereo and the party responsible for this sites maintenance of Tesuto does not control or endorse the content, messages or information found in any Communication Service and, therefore, Apereo and the party responsible for this sites maintenance of Tesuto specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized Apereo and the party responsible for this sites maintenance of Tesuto spokespersons, and their views do not necessarily reflect those of Apereo and the party responsible for this sites maintenance of Tesuto.</p>',
                    '<p>Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you download the materials.</p>',
                    '<p><strong>MATERIALS PROVIDED TO Apereo and the party responsible for this sites maintenance of Tesuto OR POSTED AT ANY Apereo and the party responsible for this sites maintenance of Tesuto web site.</strong></p>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto does not claim ownership of the materials you provide to Apereo and the party responsible for this sites maintenance of Tesuto (including feedback and suggestions) or post, upload, input or submit to any Apereo and the party responsible for this sites maintenance of Tesuto web site or its associated services (collectively &quot;Submissions&quot;). However, by posting, uploading, inputting, providing or submitting your Submission you are granting Apereo and the party responsible for this sites maintenance of Tesuto, its affiliated companies and necessary sublicensees permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission.</p>',
                    '<p>No compensation will be paid with respect to the use of your Submission, as provided herein. Apereo and the party responsible for this sites maintenance of Tesuto is under no obligation to post or use any Submission you may provide and may remove any Submission at any time in Apereo and the party responsible for this sites maintenance of Tesuto\'s sole discretion.</p>',
                    '<p>By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.</p>',
                    '<p><strong>LIABILITY DISCLAIMER</strong></p>',
                    '<p>THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE WEBSITE MAY INCLUDE INACCURACIES OR TYPOGRAPHICAL ERRORS. CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION HEREIN. Apereo and the party responsible for this sites maintenance of Tesuto AND/OR ITS SUPPLIERS MAY MAKE IMPROVEMENTS AND/OR CHANGES IN THE WEBSITE AT ANY TIME. ADVICE RECEIVED VIA THE WEBSITE SHOULD NOT BE RELIED UPON FOR PERSONAL, MEDICAL, LEGAL OR FINANCIAL DECISIONS AND YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL FOR SPECIFIC ADVICE TAILORED TO YOUR SITUATION.</p>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto AND/OR ITS SUPPLIERS MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY, RELIABILITY, AVAILABILITY, TIMELINESS, AND ACCURACY OF THE INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS CONTAINED ON THE WEBSITE FOR ANY PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OR CONDITION OF ANY KIND. Apereo and the party responsible for this sites maintenance of Tesuto AND/OR ITS SUPPLIERS HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS, INCLUDING ALL IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.</p>',
                    '<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL Apereo and the party responsible for this sites maintenance of Tesuto AND/OR ITS SUPPLIERS BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OR PERFORMANCE OF THE WEBSITE, WITH THE DELAY OR INABILITY TO USE THE WEBSITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND RELATED GRAPHICS OBTAINED THROUGH THE WEBSITE, OR OTHERWISE ARISING OUT OF THE USE OF THE WEBSITE, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF Apereo and the party responsible for this sites maintenance of Tesuto OR ANY OF ITS SUPPLIERS HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. BECAUSE SOME STATES/JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE WEBSITE, OR WITH ANY OF THESE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE WEBSITE.</p>',
                    '<p><strong>SERVICE CONTACT:</strong></p>',
                    '<p>Support Call: <a href="tel:1-480-558-2400">1-480-558-2400</a><br/>','Email: <a href="mailto:support@openccc.net">support@openccc.net</a></p>',
                    '<p><strong>TERMINATION/ACCESS RESTRICTION</strong></p>',
                    '<p>Apereo and the party responsible for this sites maintenance of Tesuto reserves the right, in its sole discretion, to terminate your access to the WEBSITE and the related services or any portion thereof at any time, without notice. GENERAL To the maximum extent permitted by law, this agreement is governed by the laws of the State of Washington, U.S.A. and you hereby consent to the exclusive jurisdiction and venue of courts in King County, Washington, U.S.A. in all disputes arising out of or relating to the use of the WEBSITE. Use of the WEBSITE is unauthorized in any jurisdiction that does not give effect to all provisions of these terms and conditions, including without limitation this paragraph. You agree that no joint venture, partnership, employment, or agency relationship exists between you and Apereo and the party responsible for this sites maintenance of Tesuto as a result of this agreement or use of the WEBSITE. Apereo and the party responsible for this sites maintenance of Tesuto\'s performance of this agreement is subject to existing laws and legal process, and nothing contained in this agreement is in derogation of Apereo and the party responsible for this sites maintenance of Tesuto\'s right to comply with governmental, court and law enforcement requests or requirements relating to your use of the WEBSITE or information provided to or gathered by Apereo and the party responsible for this sites maintenance of Tesuto with respect to such use. If any part of this agreement is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the agreement shall continue in effect. Unless otherwise specified herein, this agreement constitutes the entire agreement between the user and Apereo and the party responsible for this sites maintenance of Tesuto with respect to the WEBSITE and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written, between the user and Apereo and the party responsible for this sites maintenance of Tesuto with respect to the WEBSITE. A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. It is the express wish to the parties that this agreement and all related documents be drawn up in English.</p>',
                    '<p><strong>COPYRIGHT AND TRADEMARK NOTICES:</strong></p>',
                    '<p>All contents of the WEBSITE are: &copy; Copyright 2019 for Tesuto is licensed to the Apereo Foundation under the Creative Commons Attribution 3.0 United States License and/or its suppliers. All rights reserved.</p>',
                    '<p><strong>TRADEMARKS</strong></p>',
                    '<p>The names of actual companies and products mentioned herein may be the trademarks of their respective owners.</p>',
                    '<p>The example companies, organizations, products, people and events depicted herein are fictitious. No association with any real company, organization, product, person, or event is intended or should be inferred.</p>',
                    '<p>Any rights not expressly granted herein are reserved.</p>',
                    '<p><strong>NOTICES AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT INFRINGEMENT</strong></p>',
                    '<p>Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement under United States copyright law should be sent to Service Provider\'s Designated Agent. ALL INQUIRIES NOT RELEVANT TO THE FOLLOWING PROCEDURE WILL RECEIVE NO RESPONSE. See Notice and Procedure for Making Claims of Copyright Infringement.</p>',
                '</ccc-view-manager-static-view>',

            ].join('')
        };
    });

})();
