package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY

rule "Math Final:ef48effa-d358-472e-936f-eb102431b0::9ccd8c83-f65c-4b1e-bafe-58bb443d04d0:1"
when
	map : Map()
	student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
    cccMisCode : String() from map.get(MISCODE_KEY())
	facts : Map() from variableSet.facts
	multipleMeasureVariableSetId: String() from variableSet.id
	cum_gpa :  Double(this >= 3.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 4.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
	ruleSetId :  String(this.equals("${rule_set_id}") ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	 PlacementComponentActionResult placement = new PlacementComponentActionResult();
	 placement.setCccid(student.getCccid());
	placement.setTransferLevel("Y");
	placement.setLevelsBelowTransfer(0);
	placement.setSubjectArea("test_subject_area");
		placement.setSubjectArea("test_subject_area");
	placement.setTrackingId("test_tracking_id");
	placement.setRuleSetId(ruleSetId);
	placement.setCollegeId("test_college_id");
	placement.setRuleId("ef48effa-d358-472e-936f-eb102431b0");
	placement.setRowNumber("1");
	placement.setRuleSetRowId("9ccd8c83-f65c-4b1e-bafe-58bb443d04d0");
	placement.setCompetencyMapDiscipline("MATH");
	placement.addProgram("math_calc_i");
	 placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math Final:ef48effa-d358-472e-936f-eb102431b0::9ccd8c83-f65c-4b1e-bafe-58bb443d04d0:2"
when
	map : Map()
	student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
    cccMisCode : String() from map.get(MISCODE_KEY())
	facts : Map() from variableSet.facts
	multipleMeasureVariableSetId: String() from variableSet.id
	cum_gpa :  Double(this >= 3.2 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 5.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
	ruleSetId :  String(this.equals("${rule_set_id}") ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	 PlacementComponentActionResult placement = new PlacementComponentActionResult();
	 placement.setCccid(student.getCccid());
	placement.setTransferLevel("Y");
	placement.setLevelsBelowTransfer(0);
	placement.setSubjectArea("test_subject_area");
	placement.setTrackingId("test_tracking_id");
	placement.setRuleSetId(ruleSetId);
    placement.setSubjectArea("test_subject_area");
	placement.setTrackingId("test_tracking_id");
	placement.setCollegeId("test_college_id");
	placement.setRuleId("ef48effa-d358-472e-936f-eb102431b0");
	placement.setRowNumber("2");
	placement.setRuleSetRowId("9ccd8c83-f65c-4b1e-bafe-58bb443d04d0");
	placement.setCompetencyMapDiscipline("MATH");
	placement.addProgram("math_calc_i");
	 placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math Final:ef48effa-d358-472e-936f-eb102431b0::9ccd8c83-f65c-4b1e-bafe-58bb443d04d0:3"
when
	map : Map()
	student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
    cccMisCode : String() from map.get(MISCODE_KEY())
	facts : Map() from variableSet.facts
	multipleMeasureVariableSetId: String() from variableSet.id
	cum_gpa :  Double(this >= 3.4 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 2.2) from parseFactToDouble((Fact)facts.get("math_ranking"))
	ruleSetId :  String(this.equals("${rule_set_id}") ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	 PlacementComponentActionResult placement = new PlacementComponentActionResult();
	 placement.setCccid(student.getCccid());
	placement.setTransferLevel("Y");
	placement.setLevelsBelowTransfer(0);
	placement.setSubjectArea(subjectArea);
	placement.setTrackingId("test_tracking_id");
	placement.setRuleSetId(ruleSetId);
	placement.setCollegeId(cccMisCode);
	placement.setRuleSetId(ruleSetId);
	placement.setRuleId("ef48effa-d358-472e-936f-eb102431b0");
	placement.setRowNumber("3");
	placement.setRuleSetRowId("9ccd8c83-f65c-4b1e-bafe-58bb443d04d0");
	placement.setCompetencyMapDiscipline("MATH");
	placement.addProgram("math_pre_calc");
	 placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	filterByCollegeSubjectPlacement(actions, placement);
end
rule "Math Final:ef48effa-d358-472e-936f-eb102431b0::9ccd8c83-f65c-4b1e-bafe-58bb443d04d0:4"
when
	map : Map()
	student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
    cccMisCode : String() from map.get(MISCODE_KEY())
	facts : Map() from variableSet.facts
	multipleMeasureVariableSetId: String() from variableSet.id
	cum_gpa :  Double(this >= 2.6 )from parseFactToDouble((Fact)facts.get("gpa_cum"))
	grade : Integer(this ==11) from parseFactToInteger((Fact)facts.get("grade_level"))
	math_ranking : Double(this >= 6) from parseFactToDouble((Fact)facts.get("math_ranking"))
	ruleSetId :  String(this.equals("${rule_set_id}") ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	 PlacementComponentActionResult placement = new PlacementComponentActionResult();
	 placement.setCccid(student.getCccid());
	placement.setTransferLevel("Y");
	placement.setLevelsBelowTransfer(0);
	placement.setSubjectArea(subjectArea);
	placement.setTrackingId("test_tracking_id");
	placement.setCollegeId(cccMisCode);
	placement.setRuleSetId(ruleSetId);
	placement.setRuleId("ef48effa-d358-472e-936f-eb102431b0");
	placement.setRowNumber("4");
	placement.setRuleSetRowId("9ccd8c83-f65c-4b1e-bafe-58bb443d04d0");
	placement.setCompetencyMapDiscipline("MATH");
	placement.addProgram("math_pre_calc");
	 placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	filterByCollegeSubjectPlacement(actions, placement);
end
