package net.ccctechcenter.drools

import java.util.Map
import java.util.List
import java.util.ArrayList
import org.ccctc.common.droolscommon.RulesAction

import java.util.Date
import java.lang.Double
import java.lang.String
import java.util.stream.Collectors
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import org.cccnext.tesuto.rules.view.BasicStudentView
import org.cccnext.tesuto.domain.multiplemeasures.VariableSet
import org.cccnext.tesuto.domain.multiplemeasures.Fact
import org.cccnext.tesuto.domain.multiplemeasures.PlacementComponentActionResult
import org.cccnext.tesuto.placement.view.MmapDataSourceType
import function org.apache.commons.lang3.StringUtils.isBlank
import function org.cccnext.tesuto.rules.function.DrlFunctions.STUDENT_VIEW_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MULTIPLE_MEASURE_VARIABLE_SET_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.SUBJECT_AREA_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.TRACKING_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.MISCODE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.RULE_SET_ID_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.HIGHEST_READING_LEVEL_COURSE_KEY
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToString
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseFactToBoolean
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseDouble
import function org.cccnext.tesuto.rules.function.DrlFunctions.parseInteger
import function org.cccnext.tesuto.rules.function.DrlFunctions.filterByCollegeSubjectPlacement

rule "ERP ESL Decision Logic:005cf492-3a4e-481a-84e8-51ae24999c7b:1"
when
	 map : Map()
	    student : BasicStudentView() from map.get(STUDENT_VIEW_KEY())
	    variableSet : VariableSet() from map.get(MULTIPLE_MEASURE_VARIABLE_SET_KEY())
	    subjectArea : String() from map.get(SUBJECT_AREA_KEY())
	    cccMisCode : String() from map.get(MISCODE_KEY())
	    trackingId : String() from map.get(TRACKING_ID_KEY())
	    facts : Map() from variableSet.facts
	    multipleMeasureVariableSetId: String() from variableSet.id
	    dataSourceType: String() from variableSet.sourceType
	    dataSource: String() from variableSet.source
	    dataSourceDate: Date() from variableSet.sourceDate
	eslY_UboundY : Boolean(this == ${eslY_UboundY} )from parseFactToBoolean((Fact)facts.get("eslY_UboundY"))
	eslA_UboundY : Boolean(this == ${eslA_UboundY} )from parseFactToBoolean((Fact)facts.get("eslA_UboundY"))
	eslB_UboundY : Boolean(this == ${eslB_UboundY} )from parseFactToBoolean((Fact)facts.get("eslB_UboundY"))
	eslA_UboundA : Boolean(this == ${eslA_UboundA} )from parseFactToBoolean((Fact)facts.get("eslA_UboundA"))
	eslB_UboundA : Boolean(this == ${eslB_UboundA} )from parseFactToBoolean((Fact)facts.get("eslB_UboundA"))
	eslC_UboundA : Boolean(this == ${eslC_UboundA} )from parseFactToBoolean((Fact)facts.get("eslC_UboundA"))
	eslB_UboundB : Boolean(this == ${eslB_UboundB} )from parseFactToBoolean((Fact)facts.get("eslB_UboundB"))
	eslC_UboundB : Boolean(this == ${eslC_UboundB} )from parseFactToBoolean((Fact)facts.get("eslC_UboundB"))
	eslD_UboundB : Boolean(this == ${eslD_UboundB} )from parseFactToBoolean((Fact)facts.get("eslD_UboundB"))
	ruleSetId :  String(this == "${rule_set_id}" ) from map.get(RULE_SET_ID_KEY())
then
	List<RulesAction> actions = (List<RulesAction>) map.get("actions");
	     	PlacementComponentActionResult placement = new PlacementComponentActionResult();
	        placement.setCccid(student.getCccid());
	        placement.setTransferLevel("Y");
	        placement.setLevelsBelowTransfer(1);
	        placement.setSubjectArea(subjectArea);
	        placement.setCollegeId(cccMisCode);
	        placement.setTrackingId(trackingId);
	        placement.setRuleId("005cf492-3a4e-481a-84e8-51ae24999c7b");
	        placement.setRuleSetId(ruleSetId);
	        placement.setRuleSetRowId("${rule_set_row_id}");
	        placement.setRowNumber("1");
	        placement.setCompetencyMapDiscipline("ESL");
	        placement.addProgram("esl");
	        placement.setMultipleMeasureVariableSetId(multipleMeasureVariableSetId);
	        placement.setDataSource(dataSource);
	        placement.setDataSourceDate(dataSourceDate);
	        placement.setDataSourceType(dataSourceType);
	        placement.setStandalonePlacement(true);
	        placement.setInsufficientData(false);
	        filterByCollegeSubjectPlacement(actions, placement);
end